import { TarotCard } from '@/types'; // Assuming @/ refers to src/

export const allTarotCards: TarotCard[] = [
  {
    id: "the-fool",
    name: "The Fool",
    number: 1,
    imageFileName: "TheFool_01.jpeg",
    description: "The Fool represents the pure essence of potential and new beginnings, embodying the spirit of innocent wonder that precedes all great adventures. Like a child taking their first steps into an unknown world, The Fool encourages us to embrace life with open arms, trust in the universe's guidance, and take bold leaps of faith. This card reminds us that sometimes the most profound wisdom comes from approaching life with a beginner's mind, free from preconceptions and fear.",
  },
  {
    id: "the-magician",
    name: "The Magician",
    number: 2,
    imageFileName: "TheMagician_02.jpeg",
    description: "The Magician embodies the principle of conscious creation and manifestation, standing as a bridge between the spiritual and material realms. With all elements at their command, The Magician reminds us that we possess all the tools necessary to transform our dreams into reality. This card speaks to our innate ability to channel universal energy through focused will and intention, turning potential into tangible results through skillful action and creative power.",
  },
  {
    id: "the-high-priestess",
    name: "The High Priestess",
    number: 3,
    imageFileName: "TheHighPriestess_03.jpeg",
    description: "The High Priestess dwells in the realm of mystery and intuition, representing the deep wisdom that lies beneath the surface of consciousness. She sits between the pillars of duality, guarding the veil that separates the known from the unknown. This card invites us to trust our inner knowing, to listen to the whispers of our intuition, and to honor the sacred mysteries that cannot be explained through logic alone.",
  },
  {
    id: "the-empress",
    name: "The Empress",
    number: 4,
    imageFileName: "TheEmpress_04.jpeg",
    description: "The Empress radiates the nurturing energy of abundant creation, embodying the fertile power of nature and the creative force of the universe. She represents the flowering of all things beautiful and the rich harvest that comes from patient nurturing. This card speaks to our capacity for compassion, creativity, and sensual pleasure, reminding us that true abundance comes from nurturing ourselves and others with unconditional love.",
  },
  {
    id: "the-emperor",
    name: "The Emperor",
    number: 5,
    imageFileName: "TheEmperor_05.jpeg",
    description: "The Emperor stands as the archetype of structured power and authority, representing the principle of order that gives form to creative energy. Through wisdom earned through experience, he creates stability and protection for those under his care. This card speaks to our need for discipline, leadership, and the establishment of sustainable systems that can support long-term growth and prosperity.",
  },
  {
    id: "the-hierophant",
    name: "The Hierophant",
    number: 6,
    imageFileName: "TheHierophant_06.jpeg",
    description: "The Hierophant represents the bridge between divine wisdom and earthly understanding, embodying the role of spiritual teacher and guardian of sacred traditions. Standing at the threshold between heaven and earth, this card speaks to our connection with established spiritual practices, institutions, and the wisdom passed down through generations. It reminds us of the value in traditional knowledge while encouraging us to find our own authentic path within these established frameworks.",
  },
  {
    id: "the-lovers",
    name: "The Lovers",
    number: 7,
    imageFileName: "TheLovers_07.jpeg",
    description: "The Lovers symbolizes the profound power of choice and connection, representing not only romantic love but the deeper principle of union and alignment with our values. This card speaks to the moments when we must make heart-centered decisions that align with our highest truth. It reminds us that true love requires both conscious choice and surrender, balancing individual identity with the dance of relationship and partnership.",
  },
  {
    id: "the-chariot",
    name: "The Chariot",
    number: 8,
    imageFileName: "TheChariot_08.jpeg",
    description: "The Chariot embodies the triumph of willpower over opposing forces, representing the mastery of control and direction in our life's journey. Like a skilled charioteer harnessing contrary forces to move forward, this card speaks to our ability to channel conflicting energies into purposeful movement. It reminds us that true victory comes from maintaining focus and determination while staying balanced amidst life's challenges.",
  },
  {
    id: "strength",
    name: "Strength",
    number: 9,
    imageFileName: "Strength_09.jpeg",
    description: "Strength depicts the power of gentle force and compassionate control, showing how true strength often manifests through patience and soft persistence rather than brute force. This card speaks to our capacity to tame our inner beasts through love and understanding rather than dominance. It reminds us that real power lies in the courage to remain gentle and the strength to stay vulnerable in the face of challenges.",
  },
  {
    id: "the-hermit",
    name: "The Hermit",
    number: 10,
    imageFileName: "TheHermit_10.jpeg",
    description: "The Hermit stands as a solitary seeker of wisdom, carrying the light of inner truth through the darkness of uncertainty. This card represents the sacred journey inward, the quest for self-knowledge and understanding that requires temporary withdrawal from the outer world. It reminds us that sometimes we must step away from the crowd to hear our own inner voice and find our authentic path.",
  },
  {
    id: "wheel-of-fortune",
    name: "Wheel of Fortune",
    number: 11,
    imageFileName: "WheelOfFortune_11.jpeg",
    description: "Wheel of Fortune symbolizes the great cycles of existence, the eternal dance of change and transformation that moves through all life. This card reminds us that everything is in constant motion, that both good fortune and challenge are temporary states in the greater wheel of experience. It speaks to our need to accept and flow with life's natural rhythms while maintaining our center amidst constant change.",
  },
  {
    id: "justice",
    name: "Justice",
    number: 12,
    imageFileName: "Justice_12.jpeg",
    description: "Justice embodies the principle of universal balance and karmic law, representing the natural equilibrium that exists in all things. This card speaks to the importance of truth, fairness, and accountability in our actions and decisions. It reminds us that every cause has its effect, and that true justice comes from seeing clearly and acting with ethical integrity.",
  },
  {
    id: "the-hanged-man",
    name: "The Hanged Man",
    number: 13,
    imageFileName: "TheHangedMan_13.jpeg",
    description: "The Hanged Man offers the profound wisdom that comes through surrender and sacrifice, showing how letting go can lead to powerful transformation. This card represents the paradox of gaining through losing, of finding freedom through surrender. It speaks to those moments when we must suspend our normal ways of thinking and being to gain a new perspective on life.",
  },
  {
    id: "death",
    name: "Death",
    number: 14,
    imageFileName: "Death_14.jpeg",
    description: "Death heralds profound transformation and the natural cycle of endings and beginnings. Far from being merely about physical death, this card speaks to the necessary endings that make way for new life, like a forest fire that clears the way for new growth. It reminds us that every ending carries within it the seed of a new beginning, and that transformation, though sometimes painful, is essential for growth.",
  },
  {
    id: "temperance",
    name: "Temperance",
    number: 15,
    imageFileName: "Temperance_15.jpeg",
    description: "Temperance represents the art of balance and moderation, the skilled blending of opposing forces to create harmony. This card speaks to our ability to find the middle path, to reconcile differences and create something new from seemingly contrary elements. It reminds us that true healing comes through finding balance and integrating all aspects of ourselves.",
  },
  {
    id: "the-devil",
    name: "The Devil",
    number: 16,
    imageFileName: "TheDevil_16.jpeg",
    description: "The Devil illuminates the shadows of attachment and limitation, revealing the ways we become bound by our own desires and fears. This card speaks to the illusions of powerlessness that keep us chained to destructive patterns while reminding us that these bonds are often of our own making. It invites us to examine our attachments and face our shadows with courage and honesty.",
  },
  {
    id: "the-tower",
    name: "The Tower",
    number: 17,
    imageFileName: "TheTower_17.jpeg",
    description: "The Tower represents sudden awakening and the collapse of false structures, often arriving as a lightning bolt of truth that shatters our illusions. While its energy can feel destructive, this card speaks to the necessary breaking down of what is false or unsustainable in our lives. It reminds us that sometimes destruction is a form of creation, clearing the way for something more authentic to emerge.",
  },
  {
    id: "the-star",
    name: "The Star",
    number: 18,
    imageFileName: "TheStar_18.jpeg",
    description: "The Star shines as a beacon of hope and inspiration after the storm, representing the renewal of faith and connection to divine guidance. This card speaks to our capacity for optimism and trust in life's basic goodness, even in challenging times. It reminds us that help is always available if we remain open to receiving it, and that even in our darkest moments, the stars continue to shine above.",
  },
  {
    id: "the-moon",
    name: "The Moon",
    number: 19,
    imageFileName: "TheMoon_19.jpeg",
    description: "The Moon illuminates the realm of dreams, intuition, and the deep unconscious, casting its silvery light on both our fears and our hidden wisdom. This card speaks to the mysterious aspects of life that cannot be fully understood through rational thought alone. It reminds us to trust our intuition and to navigate the unknown with courage, knowing that what appears fearsome in the moonlight often looks different in the day.",
  },
  {
    id: "the-sun",
    name: "The Sun",
    number: 20,
    imageFileName: "TheSun_20.jpeg",
    description: "The Sun radiates pure joy and vitality, representing the triumph of clarity and truth over confusion and fear. This card speaks to our capacity for happiness, success, and authentic self-expression. It reminds us that when we align with our true nature and express ourselves freely, we naturally shine with the radiance of our inner light.",
  },
  {
    id: "judgement",
    name: "Judgement",
    number: 21,
    imageFileName: "Judgement_21.jpeg",
    description: "Judgement calls us to awakening and renewal, representing the moment of clarity when we hear our soul's true calling. This card speaks to our capacity for spiritual awakening and the recognition of our higher purpose. It reminds us that true judgment comes not from outside but from within, as we align with our authentic path and answer the call to transformation.",
  },
  {
    id: "the-world",
    name: "The World",
    number: 22,
    imageFileName: "TheWorld_22.jpeg",
    description: "The World represents completion and wholeness, the moment when all elements come together in perfect integration. This card speaks to the achievement of goals and the recognition of our interconnection with all of life. It reminds us that true fulfillment comes not just from individual achievement but from understanding our place within the greater web of existence.",
  },
  {
    id: "ace-of-wands",
    name: "Ace of Wands",
    number: 23,
    imageFileName: "AceOfWands_23.jpeg",
    description: "Ace of Wands bursts forth with the raw energy of pure creative potential, like a divine spark igniting the flame of inspiration. This card represents the initial surge of enthusiasm that precedes all new ventures, the moment when possibility first catches fire in our imagination. It speaks to the pure, unrefined energy of creation that, when properly channeled, can manifest as innovative projects, passionate relationships, or spiritual awakening.",
  },
  {
    id: "two-of-wands",
    name: "Two of Wands",
    number: 24,
    imageFileName: "TwoOfWands_24.jpeg",
    description: "Two of Wands stands at the threshold of possibility, representing the moment when initial inspiration begins to take concrete form through careful planning. Like a visionary gazing out over distant horizons, this card speaks to our ability to see beyond immediate circumstances and envision future possibilities. It encourages us to take the first steps toward manifesting our dreams while maintaining a broad perspective on our potential.",
  },
  {
    id: "three-of-wands",
    name: "Three of Wands",
    number: 25,
    imageFileName: "ThreeOfWands_25.jpeg",
    description: "Three of Wands expands our vision beyond immediate horizons, representing the moment when our initial plans begin to bear fruit and new opportunities appear on the horizon. This card speaks to the excitement of watching our efforts take root and grow, while maintaining the foresight to see even greater possibilities ahead. It reminds us that success often comes through maintaining both patience and an expansive vision.",
  },
  {
    id: "four-of-wands",
    name: "Four of Wands",
    number: 26,
    imageFileName: "FourOfWands_26.jpeg",
    description: "Four of Wands celebrates the first harvest of our efforts, representing moments of joy, harmony, and community celebration. Like a beautiful archway decorated for a festival, this card speaks to the importance of marking our achievements and sharing our success with others. It reminds us that true fulfillment often comes through creating stable foundations that can support both personal and communal joy.",
  },
  {
    id: "five-of-wands",
    name: "Five of Wands",
    number: 27,
    imageFileName: "FiveOfWands_27.jpeg",
    description: "Five of Wands brings the dynamic energy of challenge and competition, representing the conflicts and tensions that arise as different forces compete for dominance. This card speaks to the creative friction that can lead to growth and improvement, while reminding us that some conflict is necessary for development. It encourages us to engage with challenges as opportunities for strengthening our resolve and refining our skills.",
  },
  {
    id: "six-of-wands",
    name: "Six of Wands",
    number: 28,
    imageFileName: "SixOfWands_28.jpeg",
    description: "Six of Wands heralds victory and recognition, representing the moment when our efforts are crowned with success and acknowledged by others. Like a triumphant leader returning from battle, this card speaks to the importance of owning our achievements while maintaining humility. It reminds us that true victory often comes through perseverance and the support of others.",
  },
  {
    id: "seven-of-wands",
    name: "Seven of Wands",
    number: 29,
    imageFileName: "SevenOfWands_29.jpeg",
    description: "Seven of Wands stands firm in defense of what we've achieved, representing the courage to maintain our position against opposition. This card speaks to the importance of standing our ground and defending our beliefs and achievements, while reminding us that success often brings challenges that test our resolve. It encourages us to maintain our position with courage and conviction.",
  },
  {
    id: "eight-of-wands",
    name: "Eight of Wands",
    number: 30,
    imageFileName: "EightOfWands_30.jpeg",
    description: "Eight of Wands carries the swift energy of action and movement, representing rapid developments and the quick manifestation of our plans. Like arrows flying true to their target, this card speaks to moments when events align to create swift progress. It reminds us to stay focused and ready to act when opportunities present themselves.",
  },
  {
    id: "nine-of-wands",
    name: "Nine of Wands",
    number: 31,
    imageFileName: "NineOfWands_31.jpeg",
    description: "Nine of Wands embodies resilience and preparation, representing the strength we gain through facing and overcoming challenges. Like a warrior who has learned from every battle, this card speaks to the wisdom of maintaining vigilance while drawing upon our past experiences. It reminds us that our greatest strength often comes from the challenges we've already overcome.",
  },
  {
    id: "ten-of-wands",
    name: "Ten of Wands",
    number: 32,
    imageFileName: "TenOfWands_32.jpeg",
    description: "Ten of Wands carries the weight of responsibility and achievement, representing the burdens that come with success and accomplishment. This card speaks to moments when we must shoulder heavy responsibilities, while reminding us to examine whether we're carrying more than necessary. It encourages us to find ways to manage our obligations without becoming overwhelmed.",
  },
  {
    id: "page-of-wands",
    name: "Page of Wands",
    number: 33,
    imageFileName: "PageOfWands_33.jpeg",
    description: "Page of Wands sparkles with enthusiastic curiosity and creative potential, representing the spark of new ideas and the courage to explore unknown territories. Like a young adventurer setting out on their first quest, this card speaks to our capacity for wonder and our willingness to learn through experience. It reminds us to maintain our enthusiasm while being open to new ways of seeing and doing.",
  },
  {
    id: "knight-of-wands",
    name: "Knight of Wands",
    number: 34,
    imageFileName: "KnightOfWands_34.jpeg",
    description: "Knight of Wands charges forward with passionate intensity, representing the pure energy of inspired action and adventure. This card speaks to our capacity for bold movement and creative pursuit, while reminding us to temper our enthusiasm with wisdom. It encourages us to follow our passions while maintaining enough awareness to channel our energy effectively.",
  },
  {
    id: "queen-of-wands",
    name: "Queen of Wands",
    number: 35,
    imageFileName: "QueenOfWands_35.jpeg",
    description: "Queen of Wands radiates confident creativity and inspiring leadership, representing the mature expression of passionate energy. Like a natural leader who inspires through example, this card speaks to our ability to manifest our visions while supporting others in their growth. It reminds us that true confidence comes from aligning our actions with our authentic nature.",
  },
  {
    id: "king-of-wands",
    name: "King of Wands",
    number: 36,
    imageFileName: "KingOfWands_36.jpeg",
    description: "King of Wands embodies mastered creativity and visionary leadership, representing the highest expression of inspired action and authority. This card speaks to our capacity for bringing creative visions into reality while maintaining the discipline necessary for sustainable success. It reminds us that true leadership comes through balancing passion with wisdom.",
  },
  {
    id: "ace-of-cups",
    name: "Ace of Cups",
    number: 37,
    imageFileName: "AceOfCups_37.jpeg",
    description: "Ace of Cups overflows with the pure potential of emotional and spiritual connection, representing the beginning of new relationships and the opening of the heart. Like a sacred chalice brimming with divine love, this card speaks to our capacity for deep feeling and spiritual connection. It reminds us that every new emotional beginning carries the potential for profound transformation.",
  },
  {
    id: "two-of-cups",
    name: "Two of Cups",
    number: 38,
    imageFileName: "TwoOfCups_38.jpeg",
    description: "Two of Cups celebrates the power of partnership and emotional connection, representing the moment when two energies come together in harmony. This card speaks to all forms of meaningful partnership, from romantic relationships to deep friendships, reminding us that true connection creates something greater than the sum of its parts.",
  },
  {
    id: "three-of-cups",
    name: "Three of Cups",
    number: 39,
    imageFileName: "ThreeOfCups_39.jpeg",
    description: "Three of Cups dances with the joy of friendship and community celebration, representing the pleasure of sharing our happiness with others. Like friends gathered in joyful celebration, this card speaks to the importance of community and shared emotional experiences. It reminds us that joy multiplies when shared with others.",
  },
  {
    id: "four-of-cups",
    name: "Four of Cups",
    number: 40,
    imageFileName: "FourOfCups_40.jpeg",
    description: "Four of Cups contemplates the gifts before us, representing a moment of emotional reevaluation and the need to look beyond our current perspective. This card speaks to times when we might feel disconnected from our emotions or unable to appreciate what's being offered, while reminding us to look deeper for hidden opportunities.",
  },
  {
    id: "five-of-cups",
    name: "Five of Cups",
    number: 41,
    imageFileName: "FiveOfCups_41.jpeg",
    description: "Five of Cups teaches us about loss and the process of emotional healing, representing the journey through grief toward acceptance and renewal. While acknowledging the pain of loss, this card reminds us that not all is lost and that healing comes through balancing our grief with an appreciation for what remains.",
  },
  {
    id: "six-of-cups",
    name: "Six of Cups",
    number: 42,
    imageFileName: "SixOfCups_42.jpeg",
    description: "Six of Cups carries the sweet energy of nostalgia and innocent joy, representing our connection to the past and the simple pleasures of life. This card speaks to our capacity for giving and receiving kindness, while reminding us that sometimes we must look back to move forward.",
  },
  {
    id: "seven-of-cups",
    name: "Seven of Cups",
    number: 43,
    imageFileName: "SevenOfCups_43.jpeg",
    description: "Seven of Cups opens a realm of possibilities and dreams, representing both the gift and challenge of multiple choices and visions. This card speaks to our capacity for imagination while reminding us that not all that glitters is gold. It encourages us to distinguish between fantasy and achievable dreams.",
  },
  {
    id: "eight-of-cups",
    name: "Eight of Cups",
    number: 44,
    imageFileName: "EightOfCups_44.jpeg",
    description: "Eight of Cups guides us on the journey of emotional growth, representing the courage to walk away from what no longer serves our highest good. Like a pilgrim setting out on a spiritual quest, this card speaks to our ability to leave behind familiar but unfulfilling situations in search of deeper meaning.",
  },
  {
    id: "nine-of-cups",
    name: "Nine of Cups",
    number: 45,
    imageFileName: "NineOfCups_45.jpeg",
    description: "Nine of Cups radiates emotional fulfillment and the manifestation of wishes, representing a state of contentment and satisfaction. This card speaks to our capacity for happiness and the importance of appreciating our blessings, while reminding us to share our good fortune with others.",
  },
  {
    id: "ten-of-cups",
    name: "Ten of Cups",
    number: 46,
    imageFileName: "TenOfCups_46.jpeg",
    description: "Ten of Cups celebrates complete emotional fulfillment and harmonious relationships, representing the joy of deep connection and family bonds. This card speaks to our highest aspirations for emotional happiness and reminds us that true fulfillment often comes through creating and nurturing loving connections with others.",
  },
  {
    id: "page-of-cups",
    name: "Page of Cups",
    number: 47,
    imageFileName: "PageOfCups_47.jpeg",
    description: "Page of Cups brings messages from the heart and the realm of imagination, representing our capacity for emotional openness and creative inspiration. Like a child discovering the magic of life for the first time, this card speaks to our ability to approach emotional experiences with fresh eyes and an open heart.",
  },
  {
    id: "knight-of-cups",
    name: "Knight of Cups",
    number: 48,
    imageFileName: "KnightOfCups_48.jpeg",
    description: "Knight of Cups pursues romantic ideals and emotional quests, representing our search for deeper meaning and connection. This card speaks to our capacity for romantic love and artistic expression, while reminding us to balance our idealistic pursuits with practical wisdom. It encourages us to follow our heart's calling while maintaining enough groundedness to turn our dreams into reality.",
  },
  {
    id: "queen-of-cups",
    name: "Queen of Cups",
    number: 49,
    imageFileName: "QueenOfCups_49.jpeg",
    description: "Queen of Cups embodies emotional wisdom and intuitive understanding, representing our capacity for compassion and deep emotional connection. This card speaks to our ability to navigate the waters of feeling while maintaining our center, reminding us that true emotional wisdom comes through both feeling and understanding.",
  },
  {
    id: "king-of-cups",
    name: "King of Cups",
    number: 50,
    imageFileName: "KingOfCups_50.jpeg",
    description: "King of Cups masters the art of emotional balance and spiritual wisdom, representing the ability to understand and guide others while maintaining emotional stability. This card speaks to our capacity for emotional maturity and leadership, reminding us that true strength often comes through gentle wisdom.",
  },
  {
    id: "ace-of-swords",
    name: "Ace of Swords",
    number: 51,
    imageFileName: "AceOfSwords_51.jpeg",
    description: "Ace of Swords cuts through confusion with the sharp clarity of new insight, representing breakthrough moments of mental clarity and truth. Like a sword piercing the clouds, this card speaks to our capacity for clear thinking and decisive action. It reminds us that every new understanding carries both the power to create and the responsibility to use that power wisely.",
  },
  {
    id: "two-of-swords",
    name: "Two of Swords",
    number: 52,
    imageFileName: "TwoOfSwords_52.jpeg",
    description: "Two of Swords balances opposing thoughts and decisions, representing moments of choice and the need for careful consideration. This card speaks to situations where we must find equilibrium between competing ideas or options, reminding us that sometimes we need to pause and find our center before making important decisions.",
  },
  {
    id: "three-of-swords",
    name: "Three of Swords",
    number: 53,
    imageFileName: "ThreeOfSwords_53.jpeg",
    description: "Three of Swords pierces the heart with necessary truth, representing moments of pain that lead to deeper understanding. While acknowledging the reality of heartache and disappointment, this card reminds us that emotional pain often opens the way for greater wisdom and healing.",
  },
  {
    id: "four-of-swords",
    name: "Four of Swords",
    number: 54,
    imageFileName: "FourOfSwords_54.jpeg",
    description: "Four of Swords offers the gift of rest and renewal, representing the necessary pause between battles and the importance of mental recuperation. Like a warrior in peaceful repose, this card speaks to our need for quiet contemplation and the restoration that comes through stepping back from our struggles.",
  },
  {
    id: "five-of-swords",
    name: "Five of Swords",
    number: 55,
    imageFileName: "FiveOfSwords_55.jpeg",
    description: "Five of Swords confronts us with the aftermath of conflict, representing both victory and defeat in mental battles. This card speaks to the hollow nature of victory at all costs and the wisdom that can come from defeat. It reminds us to consider the long-term consequences of our triumphs and to recognize when it's better to concede than to continue fighting.",
  },
  {
    id: "six-of-swords",
    name: "Six of Swords",
    number: 56,
    imageFileName: "SixOfSwords_56.jpeg",
    description: "Six of Swords guides us through transitions and healing journeys, representing the movement from troubled waters to calmer shores. Like a ferryman guiding souls across turbulent waters, this card speaks to our capacity to move through difficult mental and emotional transitions with grace. It reminds us that sometimes the best way forward is to leave the past behind.",
  },
  {
    id: "seven-of-swords",
    name: "Seven of Swords",
    number: 57,
    imageFileName: "SevenOfSwords_57.jpeg",
    description: "Seven of Swords navigates the complex terrain of strategy and hidden truths, representing both clever planning and the need for discretion. This card speaks to situations where direct confrontation may not be the wisest path, reminding us that sometimes we must act strategically to achieve our goals while maintaining our integrity.",
  },
  {
    id: "eight-of-swords",
    name: "Eight of Swords",
    number: 58,
    imageFileName: "EightOfSwords_58.jpeg",
    description: "Eight of Swords illuminates self-imposed limitations and mental constraints, representing the ways we restrict ourselves through negative thinking. While the bindings may feel real, this card reminds us that many of our limitations are illusions we can transcend through shifting our perspective and finding the courage to see beyond our fears.",
  },
  {
    id: "nine-of-swords",
    name: "Nine of Swords",
    number: 59,
    imageFileName: "NineOfSwords_59.jpeg",
    description: "Nine of Swords confronts the shadows of anxiety and mental anguish, representing our darkest nights of worry and fear. This card speaks to the weight of our concerns while reminding us that dawn always follows even the darkest night. It encourages us to face our fears with courage and seek support when needed.",
  },
  {
    id: "ten-of-swords",
    name: "Ten of Swords",
    number: 60,
    imageFileName: "TenOfSwords_60.jpeg",
    description: "Ten of Swords marks the end of a difficult cycle, representing both the pain of ultimate defeat and the promise of new beginnings. While this card speaks to moments of profound difficulty, it reminds us that rock bottom often becomes the foundation upon which we build a stronger future.",
  },
  {
    id: "page-of-swords",
    name: "Page of Swords",
    number: 61,
    imageFileName: "PageOfSwords_61.jpeg",
    description: "Page of Swords embodies mental alertness and the quest for knowledge, representing our capacity for sharp observation and quick thinking. Like a vigilant scout watching the horizon, this card speaks to our ability to perceive truth and communicate with clarity. It encourages us to maintain our mental agility while developing our communication skills.",
  },
  {
    id: "knight-of-swords",
    name: "Knight of Swords",
    number: 62,
    imageFileName: "KnightOfSwords_62.jpeg",
    description: "Knight of Swords charges forward with intellectual intensity and swift action, representing the power of focused thought and determined pursuit of truth. This card speaks to our capacity for decisive action and clear thinking, while reminding us to balance our mental speed with careful consideration of consequences.",
  },
  {
    id: "queen-of-swords",
    name: "Queen of Swords",
    number: 63,
    imageFileName: "QueenOfSwords_63.jpeg",
    description: "Queen of Swords wields the sword of clear judgment and independent thinking, representing our ability to cut through confusion with wisdom and discernment. This card speaks to the power of objective analysis combined with life experience, reminding us that true wisdom often comes through facing and overcoming life's challenges.",
  },
  {
    id: "king-of-swords",
    name: "King of Swords",
    number: 64,
    imageFileName: "KingOfSwords_64.jpeg",
    description: "King of Swords embodies mastered intellect and ethical leadership, representing the highest expression of mental clarity and authoritative communication. This card speaks to our capacity for wise judgment and fair leadership, reminding us that true authority comes through combining intellectual power with ethical wisdom.",
  },
  {
    id: "ace-of-pentacles",
    name: "Ace of Pentacles",
    number: 65,
    imageFileName: "AceOfPentacles_65.jpeg",
    description: "Ace of Pentacles plants the seed of material opportunity and manifestation, representing new beginnings in financial and physical matters. Like a golden coin descending from heaven, this card speaks to our capacity for creating abundance and manifesting our dreams in the physical world. It reminds us that every material beginning carries the potential for long-term growth.",
  },
  {
    id: "two-of-pentacles",
    name: "Two of Pentacles",
    number: 66,
    imageFileName: "TwoOfPentacles_66.jpeg",
    description: "Two of Pentacles dances with the rhythms of balance and adaptation, representing our ability to juggle multiple responsibilities and resources. This card speaks to the dynamic nature of material success, reminding us that true abundance often comes through maintaining flexibility and finding harmony in motion.",
  },
  {
    id: "three-of-pentacles",
    name: "Three of Pentacles",
    number: 67,
    imageFileName: "ThreeOfPentacles_67.jpeg",
    description: "Three of Pentacles celebrates craftsmanship and collaborative effort, representing the power of combining skill, planning, and teamwork. This card speaks to our capacity for creating excellence through cooperation, reminding us that many of our greatest achievements come through working effectively with others.",
  },
  {
    id: "four-of-pentacles",
    name: "Four of Pentacles",
    number: 68,
    imageFileName: "FourOfPentacles_68.jpeg",
    description: "Four of Pentacles holds tight to established security, representing both the protection of resources and the potential limitations of material attachment. While acknowledging the importance of maintaining stability, this card reminds us to find balance between holding on and remaining open to growth and sharing.",
  },
  {
    id: "five-of-pentacles",
    name: "Five of Pentacles",
    number: 69,
    imageFileName: "FiveOfPentacles_69.jpeg",
    description: "Five of Pentacles walks through times of material hardship and spiritual testing, representing moments when we must find inner resources in times of outer lack. While acknowledging the reality of material challenges, this card reminds us that support is often available if we're willing to seek it.",
  },
  {
    id: "six-of-pentacles",
    name: "Six of Pentacles",
    number: 70,
    imageFileName: "SixOfPentacles_70.jpeg",
    description: "Six of Pentacles embodies the flow of giving and receiving, representing the delicate balance of generosity and gratitude. This card speaks to our capacity for sharing abundance wisely, reminding us that true wealth often multiplies when circulated with discernment and compassion.",
  },
  {
    id: "seven-of-pentacles",
    name: "Seven of Pentacles",
    number: 71,
    imageFileName: "SevenOfPentacles_71.jpeg",
    description: "Seven of Pentacles pauses to evaluate progress and long-term investments, representing the patience required for sustainable growth. Like a gardener assessing their growing crops, this card speaks to the importance of taking time to review our efforts and adjust our strategies for future harvest.",
  },
  {
    id: "eight-of-pentacles",
    name: "Eight of Pentacles",
    number: 72,
    imageFileName: "EightOfPentacles_72.jpeg",
    description: "Eight of Pentacles focuses on skill development and dedicated work, representing the path to mastery through consistent effort. This card speaks to our capacity for improving through practice and attention to detail, reminding us that excellence comes through patient dedication to our craft.",
  },
  {
    id: "nine-of-pentacles",
    name: "Nine of Pentacles",
    number: 73,
    imageFileName: "NineOfPentacles_73.jpeg",
    description: "Nine of Pentacles cultivates refined abundance and self-sufficiency, representing the rewards of disciplined effort and personal accomplishment. This card speaks to our ability to create sustainable prosperity through combining hard work with wisdom, reminding us to enjoy the fruits of our labors while maintaining our independence.",
  },
  {
    id: "ten-of-pentacles",
    name: "Ten of Pentacles",
    number: 74,
    imageFileName: "TenOfPentacles_74.jpeg",
    description: "Ten of Pentacles establishes lasting wealth and legacy, representing the achievement of material security and family prosperity. This card speaks to our capacity for creating enduring value that benefits not just ourselves but future generations, reminding us that true wealth encompasses both material and spiritual abundance.",
  },
  {
    id: "page-of-pentacles",
    name: "Page of Pentacles",
    number: 75,
    imageFileName: "PageOfPentacles_75.jpeg",
    description: "Page of Pentacles approaches material opportunities with studious dedication, representing our capacity for practical learning and manifesting new ideas. Like a dedicated student of earthly wisdom, this card speaks to our ability to approach material matters with both enthusiasm and careful attention.",
  },
  {
    id: "knight-of-pentacles",
    name: "Knight of Pentacles",
    number: 76,
    imageFileName: "KnightOfPentacles_76.jpeg",
    description: "Knight of Pentacles advances steadily toward goals with unwavering dedication, representing the power of methodical progress and reliable effort. This card speaks to our capacity for patient persistence, reminding us that consistent effort often yields the most sustainable results.",
  },
  {
    id: "queen-of-pentacles",
    name: "Queen of Pentacles",
    number: 77,
    imageFileName: "QueenOfPentacles_77.jpeg",
    description: "Queen of Pentacles nurtures prosperity through practical wisdom and generous care, representing our ability to create abundance through combining material skill with emotional intelligence. This card speaks to our capacity for creating comfort and security while maintaining connection to both earth and heart.",
  },
  {
    id: "king-of-pentacles",
    name: "King of Pentacles",
    number: 78,
    imageFileName: "KingOfPentacles_78.jpeg",
    description: "King of Pentacles masters the realm of material abundance and practical achievement, representing successful culmination of business and financial ventures. This card speaks to our capacity for creating and maintaining wealth through combining ambition with wisdom, reminding us that true prosperity comes through balancing material success with ethical leadership.",
  },
];

// Helper function to get a card by its number (1-78)
export const getCardByNumber = (number: number): TarotCard | undefined =>
  allTarotCards.find(card => card.number === number);

// Helper function to get a card by its id (slug)
export const getCardById = (id: string): TarotCard | undefined =>
  allTarotCards.find(card => card.id === id);

// You might want to add a check to ensure allTarotCards is not empty
if (allTarotCards.length < 78 && process.env.NODE_ENV === 'development') {
  console.warn(`Warning: Only ${allTarotCards.length} cards loaded into tarot-data.ts. Expected 78.`);
}
if (allTarotCards.length === 0 && process.env.NODE_ENV !== 'test') {
    throw new Error("No tarot cards loaded. Please check src/lib/tarot-data.ts");
}