import { TarotCard } from '@/types'; // Assuming @/ refers to src/

export const allTarotCards: TarotCard[] = [
  {
  id: "the-fool",
  name: "The Fool",
  number: 1,
  slug: "the-fool",
  imageFileName: "TheFool_01.jpeg",
  description: "The Fool represents the pure essence of potential and new beginnings, embodying the spirit of innocent wonder that precedes all great adventures...",
  elementAstrology: "Element: Air | Astrology: Uranus — Planet of freedom, rebellion, and unexpected shifts",
  love: "The Fool encourages openness and vulnerability in love. Step into new relationships with wonder, or rediscover joy in the one you’re already in.",
  career: "A sign to begin fresh — start a new project, take a leap, or trust your instinct in a professional gamble.",
  life: "This card symbolizes your inner child calling you to play, explore, and trust the journey, even when the path isn’t visible.",
  health: "Try something new that brings joy to your body — movement, food, nature. Health thrives when it’s light-hearted.",
  mysticMessage: "Leap, and the net will appear.",
  journalPrompt: "What would I do today if I truly trusted the universe to catch me?",
  metaDescription: "Discover the meaning of The Fool tarot card – a symbol of freedom, innocence, and new beginnings. Step into life's adventure with curiosity and trust."

},
  {
  id: "the-magician",
  name: "The Magician",
  number: 2,
  slug: "the-magician",
  imageFileName: "TheMagician_02.jpeg",
  description: "The Magician embodies the principle of conscious creation and manifestation...",
  elementAstrology: "Element: Air & Fire | Astrology: Mercury — Planet of communication, skill, and manifestation",
  love: "You have the power to create the love life you desire. The Magician signals charm, magnetism, and potential. If you're single, now’s the time to be bold and intentional. In relationships, it encourages open communication and creative ways to reconnect.",
  career: "You're a manifestor — use your full toolkit. Speak clearly, pitch ideas, start ventures. The Magician brings focus and opportunity. If you align thought and action, success will follow.",
  life: "This is a time of awakening your potential. You’re being called to harness your talents and inner wisdom. The Magician is a mirror reminding you: you already have what you need.",
  health: "Focus and balance are key. Use both natural and mindful practices to restore energy. You're encouraged to actively participate in your healing — mentally and physically.",
  mysticMessage: "As within, so without.",
  journalPrompt: "What inner resource am I ready to bring forward into the world today?",
  metaDescription: "Uncover The Magician tarot card meaning – manifestation, power, and conscious creation. You already hold the tools to shape your destiny."
},
{
  id: "the-high-priestess",
  name: "The High Priestess",
  number: 3,
  slug: "the-high-priestess",
  imageFileName: "TheHighPriestess_03.jpeg",
  description: "The High Priestess dwells in the realm of mystery and intuition...",
  elementAstrology: "Element: Water | Astrology: Moon — Planet of intuition, mystery, and inner knowledge",
  love: "Stillness. Patience. Secrets. The High Priestess invites you to observe more than speak. You may be sensing things unsaid. Trust your intuition — the truth is already within.",
  career: "You are being asked to wait before acting. Let things unfold. Behind-the-scenes insights will soon emerge. This is a time for research, planning, and learning — not action.",
  life: "This is a card of deep inner knowing. You're being drawn to sacred wisdom, dreams, or mysticism. Answers are found through silence and sacred reflection.",
  health: "Focus on hormonal balance, rest, and intuitive healing. Energetic shifts are subtle — honor your body’s rhythms.",
  mysticMessage: "The truth lies beneath the surface.",
  journalPrompt: "What is my inner voice whispering today — and how can I honor it?",
  metaDescription: "Explore the meaning of The High Priestess – a symbol of intuition, mystery, and sacred inner knowing. Trust your inner voice."
},
{
  id: "the-empress",
  name: "The Empress",
  number: 4,
  slug: "the-empress",
  imageFileName: "TheEmpress_04.jpeg",
  description: "The Empress radiates the nurturing energy of abundant creation...",
  elementAstrology: "Element: Earth | Astrology: Venus — Planet of love, fertility, beauty, and abundance",
  love: "The Empress brings warmth, affection, and sensuality. You’re being called to nurture your heart and give generously. Love blooms when you slow down and savor connection.",
  career: "Creative ideas are fertile and ready to grow. This card encourages you to build something that feels natural, beautiful, and long-lasting. Trust your creative instincts.",
  life: "You are abundant by nature. Embrace pleasure, nature, and slowness. The Empress reminds you that you are worthy of comfort and joy — without earning it.",
  health: "Nourishment is your medicine. Rest, whole foods, physical touch, and self-kindness will restore your energy.",
  mysticMessage: "Abundance flows when you nurture it with love.",
  journalPrompt: "What does it mean for me to feel deeply nourished — body, mind, and soul?",
  metaDescription: "The Empress tarot card represents fertility, beauty, and divine creativity. Embrace abundance in love, life, and nature."
},
{
  id: "the-emperor",
  name: "The Emperor",
  number: 5,
  slug: "the-emperor",
  imageFileName: "TheEmperor_05.jpeg",
  description: "The Emperor stands as the archetype of structured power and authority...",
  elementAstrology: "Element: Fire | Astrology: Aries — Sign of leadership, protection, and structure",
  love: "The Emperor brings protection and stability, but can also signal control or rigidity. Examine your relationship roles: are they empowering or restricting?",
  career: "Now is the time to lead. The Emperor favors structure, planning, and authoritative decisions. Take command — your leadership is needed.",
  life: "Bring order to chaos. Create strong foundations. This is about boundaries, discipline, and showing up for yourself with unwavering resolve.",
  health: "Build strength — physically and mentally. Focus on routines, core health, and protective habits. Small disciplined acts create lasting power.",
  mysticMessage: "True power lies in responsible leadership.",
  journalPrompt: "Where in my life do I need to step up and lead with grounded authority?",
  metaDescription: "The Emperor stands for structure, leadership, and stability. Step into your power and create order from chaos."

},
{
  id: "the-hierophant",
  name: "The Hierophant",
  number: 6,
  slug: "the-hierophant",
  imageFileName: "TheHierophant_06.jpeg",
  description: "The Hierophant represents the bridge between divine wisdom and earthly understanding...",
  elementAstrology: "Element: Earth | Astrology: Taurus — Sign of tradition, devotion, and sacred structure",
  love: "The Hierophant suggests commitment, spiritual connection, or the influence of tradition in love. It could indicate marriage, mentorship, or needing alignment in shared values.",
  career: "This card calls for structure, learning, or mentorship. Now is a good time to study under someone experienced, follow best practices, or honor legacy systems — before innovating.",
  life: "You’re being called to explore spiritual beliefs or ancestral wisdom. What rituals, stories, or sacred systems shaped you? There’s guidance waiting in the old ways.",
  health: "Rely on established healing systems or expert advice. Structure, consistency, and patience are key. Long-term well-being comes through spiritual alignment too.",
  mysticMessage: "Sacred truth is passed through lineage and lived devotion.",
  journalPrompt: "What ancient or inherited wisdom feels most alive and true to me right now?",
  metaDescription: "Discover the meaning of The Hierophant – tradition, spiritual wisdom, and sacred teachings. Seek alignment through mentorship or ritual."
},

  {
  id: "the-lovers",
  name: "The Lovers",
  number: 7,
  slug: "the-lovers",
  imageFileName: "TheLovers_07.jpeg",
  description: "The Lovers symbolizes the profound power of choice and connection...",
  elementAstrology: "Element: Air | Astrology: Gemini — Sign of duality, choice, and sacred connection",
  love: "This is a heart-centered moment. Whether you're in union or at a crossroads, love asks you to choose with truth. Real connection comes from shared values and deep alignment.",
  career: "You're at a fork in the road. Let your decision be guided by passion and purpose, not just logic. What path feels most aligned with your soul?",
  life: "This card mirrors your relationship to yourself. Heal inner divides, embrace wholeness, and trust your inner compass.",
  health: "Balance is key — emotionally, hormonally, and energetically. Reconnect with your body and inner voice. Are your habits in harmony with your heart?",
  mysticMessage: "Love is the great teacher. Every choice is an echo of what you value.",
  journalPrompt: "What does loving alignment look like — with myself, and with others?",
  metaDescription: "The Lovers tarot card reflects union, choice, and harmony. Explore deep connection and the power of aligned decisions."
},
{
  id: "the-chariot",
  name: "The Chariot",
  number: 8,
  slug: "the-chariot",
  imageFileName: "TheChariot_08.jpeg",
  description: "The Chariot embodies the triumph of willpower over opposing forces...",
  elementAstrology: "Element: Water | Astrology: Cancer — Sign of willpower, direction, and protective determination",
  love: "You may be moving forward fast — emotionally or literally. This card asks: are you steering from fear or from love? Stay emotionally clear and aligned in your direction.",
  career: "Charge ahead with focus and confidence. Victory is possible when you harness discipline and emotion in the same direction. Eyes on the goal.",
  life: "You are being asked to take the reins. Self-control and intentional motion are your superpowers right now. Don’t get pulled off track.",
  health: "Movement matters — literal or energetic. Cleanse stuck emotions, focus your will, and don’t ignore signs from your body about imbalance.",
  mysticMessage: "Your will is the chariot. Hold the reins and ride.",
  journalPrompt: "What part of me is asking to be directed with courage and clarity?",
  metaDescription: "The Chariot speaks of focused will, triumph, and determination. Take control of your path and steer it with purpose."
},
{
  id: "strength",
  name: "Strength",
  number: 9,
  slug: "strength",
  imageFileName: "Strength_09.jpeg",
  description: "Strength depicts the power of gentle force and compassionate control...",
  elementAstrology: "Element: Fire | Astrology: Leo — Sign of heart-centered courage, grace, and inner fire",
  love: "You’re being asked to lead with compassion and patience. True strength in love is shown through gentleness, not force. Let vulnerability be your superpower.",
  career: "Courage under pressure. This is the time for calm resolve — not brute action. You’re being asked to tame wild energy and show graceful leadership.",
  life: "This card celebrates your resilience. You’ve come far, and you’ve done it with heart. Keep going — but soften when needed.",
  health: "Support your nervous system. Choose practices that build quiet, steady strength — yoga, breathwork, rest. Be kind to your inner lion.",
  mysticMessage: "Strength is love in motion — patient, grounded, and full of grace.",
  journalPrompt: "Where am I being asked to soften — and still stand strong?",
  metaDescription: "Strength represents inner resilience, compassion, and courage. Power comes through patience and self-trust."
},
{
  id: "the-hermit",
  name: "The Hermit",
  number: 10,
  slug: "the-hermit",
  imageFileName: "TheHermit_10.jpeg",
  description: "The Hermit stands as a solitary seeker of wisdom...",
  elementAstrology: "Element: Earth | Astrology: Virgo — Sign of introspection, healing, and spiritual clarity",
  love: "This card may point to time apart or inner reflection. It’s not isolation — it’s sacred space. Take time to realign with what love truly means for you.",
  career: "Step back to refine. The Hermit advises introspection and solo work. You're finding your own voice and wisdom — away from the noise.",
  life: "This is your soul’s quiet retreat. Go within. The answers you seek will glow softly from within your own lantern of truth.",
  health: "Nourish solitude, stillness, and slowness. Healing comes from retreat, spiritual focus, and simplifying your routines.",
  mysticMessage: "Go within. The light you seek is already in your hand.",
  journalPrompt: "What wisdom have I been carrying all along, but not fully trusting?",
  metaDescription: "The Hermit invites solitude, introspection, and spiritual insight. Step inward to find your guiding light."

},
{
  id: "wheel-of-fortune",
  name: "Wheel of Fortune",
  number: 11,
  slug: "wheel-of-fortune",
  imageFileName: "WheelOfFortune_11.jpeg",
  description: "Wheel of Fortune symbolizes the great cycles of existence...",
  elementAstrology: "Element: Fire | Astrology: Jupiter — Planet of luck, expansion, and divine timing",
  love: "Expect change — a twist of fate may be at play. What’s meant for you won’t pass you by. Stay open to shifts in connection, attraction, or perspective.",
  career: "Sudden opportunities or reversals may arise. Stay agile. This is a reminder that your destiny can turn — rise to meet it with courage.",
  life: "Life moves in cycles. You’re not stuck — just mid-turn. Trust the flow of time and remember that each phase is meaningful, even if unclear now.",
  health: "You may feel ups and downs — focus on rhythm, rest, and recalibration. Trust your body’s wisdom to adjust through cycles of growth and release.",
  mysticMessage: "Change is the only constant — dance with the wheel.",
  journalPrompt: "What cycle am I completing — and what new one is ready to begin?",
  metaDescription: "Wheel of Fortune symbolizes fate, luck, and life’s turning cycles. Embrace change and trust the unfolding journey."
},
{
  id: "justice",
  name: "Justice",
  number: 12,
  slug: "justice",
  imageFileName: "Justice_12.jpeg",
  description: "Justice embodies the principle of universal balance and karmic law...",
  elementAstrology: "Element: Air | Astrology: Libra — Sign of fairness, truth, and equilibrium",
  love: "This card calls for honest reflection. Are you giving and receiving in balance? Justice invites fairness, clarity, and accountability in all partnerships.",
  career: "Contracts, legal matters, or ethical choices may arise. Act with integrity. What’s fair for you — and fair for all?",
  life: "You’re being asked to weigh your decisions with clarity. Truth and consequences are intertwined. Act with conscious awareness of cause and effect.",
  health: "Seek alignment — mentally, physically, emotionally. Small imbalances can ripple. Focus on lifestyle corrections that restore inner harmony.",
  mysticMessage: "Truth holds the sword and the scales — speak and act with clarity.",
  journalPrompt: "What truth within me is asking to be honored — regardless of outcome?",
  metaDescription: "Justice tarot card calls for truth, fairness, and accountability. What you give, you receive."
},
{
  id: "the-hanged-man",
  name: "The Hanged Man",
  number: 13,
  slug: "the-hanged-man",
  imageFileName: "TheHangedMan_13.jpeg",
  description: "The Hanged Man offers the profound wisdom that comes through surrender...",
  elementAstrology: "Element: Water | Astrology: Neptune — Planet of spiritual dissolution and altered states",
  love: "Pause. Release expectations. This is not the time for control or answers. Let the truth unfold through stillness and new perspective.",
  career: "Take a break from action. Things may feel stuck — but this is a sacred pause. Insight comes through letting go of attachment to outcome.",
  life: "Surrender is your initiation. Shift your perspective. The world looks different when you stop trying to shape it, and simply see.",
  health: "Focus on stress release, rest, and nervous system repair. A mindset shift or energy healing could bring deep results.",
  mysticMessage: "Let go. The wisdom you seek is waiting in the pause.",
  journalPrompt: "What must I release control of, in order to gain true understanding?",
  metaDescription: "The Hanged Man reveals surrender, new perspective, and spiritual pause. Growth blooms in stillness."
},
{
  id: "death",
  name: "Death",
  number: 14,
  slug: "death",
  imageFileName: "Death_14.jpeg",
  description: "Death heralds profound transformation and the natural cycle of endings and beginnings...",
  elementAstrology: "Element: Water | Astrology: Scorpio — Sign of transformation, rebirth, and emotional depth",
  love: "Something may be ending — or evolving beyond recognition. This card invites honesty about what needs to die for love to truly thrive.",
  career: "A chapter is closing. Allow it. Whether a job, identity, or goal — endings clear space for your next evolution.",
  life: "You are shedding skin. Do not fear the void between death and rebirth. This is sacred compost — your next self is already emerging.",
  health: "Focus on detoxification, grief processing, and letting go. Something old is leaving your system. Make space for renewal.",
  mysticMessage: "All endings are disguised beginnings. Let the old pass with reverence.",
  journalPrompt: "What must I fully release in order to truly transform?",
  metaDescription: "Death marks endings, transformation, and rebirth. Let go of what no longer serves to allow space for what will."
},
{
  id: "temperance",
  name: "Temperance",
  number: 15,
  slug: "temperance",
  imageFileName: "Temperance_15.jpeg",
  description: "Temperance represents the art of balance and moderation...",
  elementAstrology: "Element: Fire | Astrology: Sagittarius — Sign of integration, wisdom, and long journeys",
  love: "Healing, compromise, and emotional blending are called for. This card invites unity through balance — no extremes, no power games.",
  career: "Steady integration brings success. Blend your skills, balance boldness with patience, and keep your long-term vision in sight.",
  life: "You are alchemizing. Opposites within you are finding harmony. This is a time of inner integration and calm expansion.",
  health: "Balance and moderation are medicine. Focus on routines that support harmony — no extremes. Rehydration and recalibration are key.",
  mysticMessage: "You are the vessel. Let all things blend in sacred proportion.",
  journalPrompt: "What area of my life is asking for healing through balance?",
  metaDescription: "Temperance brings balance, healing, and integration. Blend dualities into harmonious flow.",
},
{
  id: "the-devil",
  name: "The Devil",
  number: 16,
  slug: "the-devil",
  imageFileName: "TheDevil_16.jpeg",
  description: "The Devil illuminates the shadows of attachment and limitation...",
  elementAstrology: "Element: Earth | Astrology: Capricorn — Sign of control, ambition, and material form",
  love: "Look at patterns of control, lust, or addiction. Are you bound to something unhealthy in love? Awareness is the first step to liberation.",
  career: "Are you chasing success or caught in burnout? This card exposes ambition turned obsession. Reclaim your freedom — redefine success.",
  life: "You are not trapped — only conditioned. Your chains are illusions you can break. Face your shadows and reclaim your inner power.",
  health: "Check for dependencies — substances, screens, stimulants, or thought patterns. Healing starts with honest confrontation.",
  mysticMessage: "What you fear owns you. Face it — and set yourself free.",
  journalPrompt: "What inner or outer chain am I ready to break — and who am I without it?",
  metaDescription: "The Devil represents temptation, shadow, and self-liberation. What binds you – and how can you break free?"
},
{
  id: "the-tower",
  name: "The Tower",
  number: 17,
  slug: "the-tower",
  imageFileName: "TheTower_17.jpeg",
  description: "The Tower represents sudden awakening and the collapse of false structures...",
  elementAstrology: "Element: Fire | Astrology: Mars — Planet of destruction, courage, and raw force",
  love: "Unexpected truths may arise. Something may be crumbling — but only what wasn’t real. Let false intimacy fall so real love can grow.",
  career: "Shocks or breakdowns may occur — but they’re sacred disruptions. What’s being cleared was unstable. Something better is being made possible.",
  life: "This is sacred upheaval. A lightning strike from the divine. Let what must fall — fall. And from the rubble, rise real truth.",
  health: "Emotional breakdowns may precede breakthroughs. Rest, breathe, and rebuild. Remove toxic inputs — they may be the root.",
  mysticMessage: "Let it fall. What collapses clears space for what is unshakably true.",
  journalPrompt: "What truth has been trying to break through — even if it shatters my current structure?",
  metaDescription: "The Tower shatters illusions to spark truth and breakthrough. Though chaotic, its storm clears the way forward."
},
{
  id: "the-star",
  name: "The Star",
  number: 18,
  slug: "the-star",
  imageFileName: "TheStar_18.jpeg",
  description: "The Star shines as a beacon of hope and inspiration after the storm...",
  elementAstrology: "Element: Air | Astrology: Aquarius — Sign of inspiration, vision, and cosmic connection",
  love: "Hope is returning. Emotional renewal is possible. You may be healing from heartbreak or rediscovering light in connection.",
  career: "Inspiration flows. This card blesses long-term visions and soul-aligned dreams. Keep going — your unique gifts matter.",
  life: "You are the star — a soul with divine light. Stay open to inspiration. Miracles follow when you trust the bigger picture.",
  health: "Emotional healing, rehydration, and energetic clarity are emphasized. Let nature, stillness, and faith support your restoration.",
  mysticMessage: "You are never alone. The cosmos sings to your soul — listen.",
  journalPrompt: "Where am I being invited to believe again — even after the storm?",
  metaDescription: "The Star tarot card offers hope, healing, and cosmic renewal. You are supported by divine light."
},
{
  id: "the-moon",
  name: "The Moon",
  number: 19,
  slug: "the-moon",
  imageFileName: "TheMoon_19.jpeg",
  description: "The Moon illuminates the realm of dreams, intuition, and the deep unconscious...",
  elementAstrology: "Element: Water | Astrology: Pisces — Sign of dreams, illusion, and mysticism",
  love: "Things may not be what they seem. Secrets or projections may be at play. Let your intuition guide you — not fear or fantasy.",
  career: "Uncertainty is present. Avoid rash decisions. Instead, feel into your instincts and explore beneath the surface before acting.",
  life: "This is a liminal space — between knowing and not knowing. Let the dream world guide you. Clarity will come, but not through logic.",
  health: "Hormonal cycles, sleep, and emotional flow are emphasized. Honor your sensitivity. Protect your peace.",
  mysticMessage: "The path may be unclear — but your intuition sees in the dark.",
  journalPrompt: "What is my intuition trying to show me beneath the illusion?",
  metaDescription: "The Moon reflects mystery, dreams, and illusions. Listen to your intuition and trust your subconscious knowing."
},
{
  id: "the-sun",
  name: "The Sun",
  number: 20,
  slug: "the-sun",
  imageFileName: "TheSun_20.jpeg",
  description: "The Sun radiates pure joy and vitality...",
  elementAstrology: "Element: Fire | Astrology: The Sun — Source of life, joy, and illumination",
  love: "Joy, warmth, and playful connection abound. This is a radiant moment in love — express your heart freely and openly.",
  career: "Success, visibility, and creative recognition shine. If you’ve been working toward something, this card confirms: you’re being seen.",
  life: "You are aligned. The light within you is leading the way. Trust this moment of clarity and vitality — it’s your time to shine.",
  health: "Vitality surges. Embrace movement, sunshine, and joyful habits. Let your wellness radiate from inner joy.",
  mysticMessage: "Shine without shame. You were born to glow.",
  journalPrompt: "Where in my life am I ready to radiate fully — without fear of being seen?",
  metaDescription: "The Sun radiates joy, success, and clarity. Celebrate your light and live vibrantly in your truth."
},

  
  
  {
  id: "judgement",
  name: "Judgement",
  number: 21,
  slug: "judgement",
  imageFileName: "Judgement_21.jpeg",
  description: "Judgement calls us to awakening and renewal...",
  elementAstrology: "Element: Fire | Astrology: Pluto — Planet of rebirth, soul purpose, and transformation",
  love: "It’s time for honest reflection. Past patterns, past partners, or truths may resurface for healing or closure. Reconciliation is possible — but only through truth.",
  career: "A call to purpose is sounding. What work feels truly aligned with your soul? It may be time to pivot, elevate, or finally answer your higher calling.",
  life: "You’re awakening. Shed shame, guilt, or old versions of self. This is the rebirth after reckoning — step into your truth with clarity.",
  health: "Deep healing is possible. Old emotional wounds may rise — release them consciously. Your body and spirit are asking for renewal.",
  mysticMessage: "The trumpet sounds. Awaken to who you were born to be.",
  journalPrompt: "What truth within me is asking to rise from the ashes of who I used to be?",
  metaDescription: "Judgement invites reflection, awakening, and second chances. Hear the call of your higher purpose."
},
{
  id: "the-world",
  name: "The World",
  number: 22,
  slug: "the-world",
  imageFileName: "TheWorld_22.jpeg",
  description: "The World represents completion and wholeness...",
  elementAstrology: "Element: Earth | Astrology: Saturn — Planet of completion, mastery, and karmic fulfillment",
  love: "Wholeness within creates harmony in love. You may be experiencing deep fulfillment in connection, or completing a cycle that opens space for true love.",
  career: "A project may be reaching its final form. Celebrate the completion — you’ve reached a milestone. You’re also ready for the next level.",
  life: "You have come full circle. This is a moment of deep integration, unity, and purpose. Celebrate all that’s led you here — and all that lies ahead.",
  health: "Stability and balance are here. Let your routines reflect the wholeness you feel. It’s a good time to ground and embody your progress.",
  mysticMessage: "You are the cosmos expressing itself — complete, radiant, and ready.",
  journalPrompt: "Where do I feel complete — and how do I honor that arrival?",
  metaDescription: "The World card represents completion, mastery, and wholeness. You’ve come full circle — now begin anew."
},
{
  id: "ace-of-wands",
  name: "Ace of Wands",
  number: 23,
  slug: "ace-of-wands",
  imageFileName: "AceOfWands_23.jpeg",
  description: "Ace of Wands bursts forth with the raw energy of pure creative potential...",
  elementAstrology: "Element: Fire | Astrology: Mars — Spark of passion, ambition, and ignition",
  love: "A new spark is igniting — a passionate beginning or renewed fire in an existing bond. Follow desire, but ground it in presence.",
  career: "Inspiration strikes! A new idea, offer, or path wants your attention. Say yes — and fan the flame with focused action.",
  life: "This is a green light from the universe. Follow what excites you. It’s time to begin something bold and beautifully alive.",
  health: "Channel excess energy into movement or creation. Your vitality is rising — let it express through the body.",
  mysticMessage: "The fire has been lit. What you do with it is up to you.",
  journalPrompt: "What is bursting to life within me — and how can I honor it with action?",
  metaDescription: "The Ace of Wands sparks fresh inspiration, bold ideas, and passionate beginnings. A green light from the universe to go create."
},
{
  id: "two-of-wands",
  name: "Two of Wands",
  number: 24,
  slug: "two-of-wands",
  imageFileName: "TwoOfWands_24.jpeg",
  description: "Two of Wands stands at the threshold of possibility...",
  elementAstrology: "Element: Fire | Astrology: Mars in Aries — Energy of bold planning and ambition",
  love: "You may be envisioning what love could be — or craving expansion in a current bond. Clarify your desires before making a move.",
  career: "You’re in the early stages of growth. The vision is there — now’s the time to make a plan, take initiative, and trust your inner leader.",
  life: "The world is in your hands. Don’t stay stuck in daydreams — map out the next step. You are capable of bold direction.",
  health: "A fresh perspective on wellness is forming. Plan your routines, habits, or healing paths with intention and follow-through.",
  mysticMessage: "You’re not just dreaming — you’re deciding. Step forward.",
  journalPrompt: "What vision am I holding — and what’s the very first step I can take?",
  metaDescription: "The Two of Wands represents planning, vision, and potential expansion. It’s time to look ahead and move with intention."
},
{
  id: "three-of-wands",
  name: "Three of Wands",
  number: 25,
  slug: "three-of-wands",
  imageFileName: "ThreeOfWands_25.jpeg",
  description: "Three of Wands expands our vision beyond immediate horizons...",
  elementAstrology: "Element: Fire | Astrology: Sun in Aries — Expansive initiative and confidence",
  love: "Your relationship or love journey is entering a phase of growth. New adventures, deeper connection, or long-distance possibilities arise.",
  career: "You’ve taken the first steps — now expansion is possible. Opportunities may come from afar or as a result of past effort. Keep going.",
  life: "Your past actions are setting your future in motion. Expect rewards, movement, or exciting new options. Stay open and alert.",
  health: "Improvements are on the horizon. Celebrate the progress you’ve made and keep your momentum going with aligned action.",
  mysticMessage: "Your energy is reaching beyond your current world. Expansion is in motion.",
  journalPrompt: "What future am I preparing to meet — and how can I greet it with faith?",
  metaDescription: "The Three of Wands shows progress, momentum, and anticipation. Your efforts are unfolding — keep going."
},
{
  id: "four-of-wands",
  name: "Four of Wands",
  number: 26,
  slug: "four-of-wands",
  imageFileName: "FourOfWands_26.jpeg",
  description: "Four of Wands celebrates the first harvest of our efforts...",
  elementAstrology: "Element: Fire | Astrology: Venus in Aries — Joyful union, celebration, and domestic bliss",
  love: "Commitment, harmony, or joyful partnership is available. This card can indicate weddings, reunions, or homecoming with someone you love.",
  career: "Celebrate your wins — even the small ones. Your efforts are bearing fruit. Gather with your community and honor your journey.",
  life: "Pause to honor your progress. You’ve created something stable and beautiful — don’t rush past the joy of it.",
  health: "Stability is returning. Focus on environment, joy, and nervous system safety. Healing happens when you feel at home in your life.",
  mysticMessage: "Celebrate what has taken root — joy is sacred too.",
  journalPrompt: "How can I celebrate my current wins — even the subtle ones?",
  metaDescription: "The Four of Wands is a card of celebration, harmony, and homecoming. Enjoy the blessings of stability and shared joy."
},
{
  id: "five-of-wands",
  name: "Five of Wands",
  number: 27,
  slug: "five-of-wands",
  imageFileName: "FiveOfWands_27.jpeg",
  description: "Five of Wands brings the dynamic energy of challenge and competition...",
  elementAstrology: "Element: Fire | Astrology: Saturn in Leo — Lessons in ego, challenge, and creative conflict",
  love: "Tension may arise. Petty conflicts or miscommunications can create friction. Clear the air with honesty, not blame.",
  career: "Competing visions or power struggles may surface. Use this friction to refine your leadership and assert your truth constructively.",
  life: "This is a training ground. Don’t shy away from challenges — they’re strengthening your voice, vision, and self-worth.",
  health: "Stress or energetic conflict may show up in the body. Movement, grounding, and boundary work can help recalibrate.",
  mysticMessage: "Growth sometimes comes through the heat of friction.",
  journalPrompt: "How can I transform challenge into growth — without losing my center?",
  metaDescription: "The Five of Wands indicates conflict, competition, and creative tension. Stay centered in the storm."
},
{
  id: "six-of-wands",
  name: "Six of Wands",
  number: 28,
  slug: "six-of-wands",
  imageFileName: "SixOfWands_28.jpeg",
  description: "Six of Wands heralds victory and recognition...",
  elementAstrology: "Element: Fire | Astrology: Jupiter in Leo — Expansion through confidence and visibility",
  love: "Your light is being seen. Whether it’s a partner acknowledging your worth or a new admirer arriving — shine without shrinking.",
  career: "Your hard work is paying off. Expect public recognition, praise, or a milestone win. Stay humble, but own your success.",
  life: "You’ve overcome something — now it’s time to rise with confidence. You deserve to be proud. Others are inspired by your journey.",
  health: "Your strength is returning. Celebrate progress and focus on maintaining momentum. Share what’s worked for you with others.",
  mysticMessage: "You’ve earned this moment — now let it lift you.",
  journalPrompt: "What part of me is ready to be fully acknowledged and celebrated?",
  metaDescription: "The Six of Wands signifies victory, recognition, and rising up. Your efforts are paying off — own your spotlight."
},
{
  id: "seven-of-wands",
  name: "Seven of Wands",
  number: 29,
  slug: "seven-of-wands",
  imageFileName: "SevenOfWands_29.jpeg",
  description: "Seven of Wands stands firm in defense of what we've achieved...",
  elementAstrology: "Element: Fire | Astrology: Mars in Leo — Defending passion and personal power",
  love: "Boundaries matter. Stand your ground if you’re feeling tested or overwhelmed. Healthy conflict can lead to deeper trust.",
  career: "You’ve earned your place — now defend it with confidence. Don’t shrink when challenged. You’re stronger than you think.",
  life: "Not everyone will understand your path — and that’s okay. Hold your position. Your integrity matters more than approval.",
  health: "Support your immune system and energy. Stand up for your well-being — especially if it’s being overlooked.",
  mysticMessage: "Your light may attract challenge — but it’s worth defending.",
  journalPrompt: "Where in my life do I need to stand firm — even if it’s uncomfortable?",
  metaDescription: "The Seven of Wands speaks of defending your position, standing strong, and staying aligned with your truth."
},

{
  id: "eight-of-wands",
  name: "Eight of Wands",
  number: 30,
  slug: "eight-of-wands",
  imageFileName: "EightOfWands_30.jpeg",
  description: "Eight of Wands carries the swift energy of action and movement...",
  elementAstrology: "Element: Fire | Astrology: Mercury in Sagittarius — Fast progress, clear direction, and open communication",
  love: "Momentum is building. If you're single, love could arrive suddenly. In a relationship, this may signal a breakthrough conversation or exciting shift.",
  career: "News, offers, or results may come quickly. Projects gain speed, travel may be involved, and it’s time to act fast on opportunity.",
  life: "You're in motion — finally. Trust the acceleration. Doors are opening, and the energy supports fast, clear decisions.",
  health: "Improvement may be rapid — especially if you’ve recently changed something. Keep moving and maintain flow. Avoid burnout.",
  mysticMessage: "The way is clear. Act before hesitation slows the magic.",
  journalPrompt: "What opportunity is asking me to move now — before the window closes?",
  metaDescription: "The Eight of Wands brings swift action, communication, and rapid movement. Things are accelerating — stay focused."
},

{
  id: "nine-of-wands",
  name: "Nine of Wands",
  number: 31,
  slug: "nine-of-wands",
  imageFileName: "NineOfWands_31.jpeg",
  description: "Nine of Wands embodies resilience and preparation...",
  elementAstrology: "Element: Fire | Astrology: Moon in Sagittarius — Emotional endurance and spiritual perseverance",
  love: "You may feel guarded or tired. Rest, but don’t give up. You’ve come far — and love is still worth showing up for.",
  career: "You’re close to the finish line. This is a test of endurance. Protect your energy and stay committed — success is within reach.",
  life: "You’ve been through the fire. Your soul is strong — even if weary. This is the moment to breathe, regroup, and prepare to rise again.",
  health: "Fatigue may be present. Listen to your limits. Rest is a form of resilience — not weakness.",
  mysticMessage: "You’re not broken — you’re battle-tested and brave.",
  journalPrompt: "How can I honor my inner warrior — without pushing past my own limits?",
  metaDescription: "The Nine of Wands represents resilience, grit, and preparation. You’re almost there — hold steady."
},
{
  id: "ten-of-wands",
  name: "Ten of Wands",
  number: 32,
  slug: "ten-of-wands",
  imageFileName: "TenOfWands_32.jpeg",
  description: "Ten of Wands carries the weight of responsibility and achievement...",
  elementAstrology: "Element: Fire | Astrology: Saturn in Sagittarius — Burdens through ambition and duty",
  love: "You may be carrying too much emotional labor. Healthy love requires balance — it’s time to delegate, communicate, or release what’s not yours to hold.",
  career: "Success has come with a price. You're working hard, maybe too hard. Reassess your load — and make sure you’re not sacrificing your well-being for achievement.",
  life: "You’ve come far, but the journey has become heavy. It’s time to lay down what no longer serves. Rest, delegate, simplify.",
  health: "Back pain, fatigue, or stress overload could be signs you're doing too much. Your body is asking for relief — listen.",
  mysticMessage: "Release the burden. You don’t have to carry it all alone.",
  journalPrompt: "What am I holding that I no longer need — and what would it feel like to set it down?",
  metaDescription: "The Ten of Wands shows burdens, overwhelm, and the weight of responsibility. Time to delegate or release what drains you."
},
{
  id: "page-of-wands",
  name: "Page of Wands",
  number: 33,
  slug: "page-of-wands",
  imageFileName: "PageOfWands_33.jpeg",
  description: "Page of Wands sparkles with enthusiastic curiosity and creative potential...",
  elementAstrology: "Element: Fire | Astrology: Earth of Fire — The learner of courage, creativity, and passion",
  love: "A flirtatious connection or exciting message may arise. The energy is playful — lean into discovery without expectation.",
  career: "You may be starting something new — a fresh project, idea, or offer. Stay curious, open-minded, and willing to experiment.",
  life: "This is a time of exploration and spark. Let your inner adventurer guide you. New paths will open when you follow your excitement.",
  health: "Energy is rising — move, stretch, explore. Try something new that brings joy to your body and spirit.",
  mysticMessage: "Your spark is sacred — nurture it with joy, not pressure.",
  journalPrompt: "What am I excited to try — even if I have no idea where it will lead?",
  metaDescription: "The Page of Wands is youthful energy, curiosity, and the spirit of discovery. Follow your spark with openness."
},
{
  id: "knight-of-wands",
  name: "Knight of Wands",
  number: 34,
  slug: "knight-of-wands",
  imageFileName: "KnightOfWands_34.jpeg",
  description: "Knight of Wands charges forward with passionate intensity...",
  elementAstrology: "Element: Fire | Astrology: Air of Fire — Boldness, charisma, and fearless momentum",
  love: "Passion is high, but may burn fast. This can indicate a fiery connection or a need to act boldly in love — just beware of impulsivity.",
  career: "Now’s the time to move quickly and with confidence. Launch the project, pitch the idea, go all in — just be sure your plan is grounded.",
  life: "You are being asked to follow your fire — even if it scares you. Let desire drive, but check in with your deeper why.",
  health: "Channel energy into physical movement or goal-setting. But don’t overdo it — balance impulse with endurance.",
  mysticMessage: "Move boldly, but not blindly. Your fire is a gift — learn to direct it.",
  journalPrompt: "Where am I being called to leap — and what will keep me centered as I fly?",
  metaDescription: "The Knight of Wands is adventure, drive, and fiery ambition. Charge forward — but don’t burn out."
},
{
  id: "queen-of-wands",
  name: "Queen of Wands",
  number: 35,
  slug: "queen-of-wands",
  imageFileName: "QueenOfWands_35.jpeg",
  description: "Queen of Wands radiates confident creativity and inspiring leadership...",
  elementAstrology: "Element: Fire | Astrology: Water of Fire — Intuitive leadership, radiant power, magnetic presence",
  love: "You are magnetic. Step into your self-worth and express your truth confidently. If you’re seeking love — shine without apology.",
  career: "Leadership opportunities may be presenting themselves. You inspire others by being fully yourself. Bold ideas are welcome — speak up.",
  life: "This is your permission to take up space. Lead with charisma, intuition, and creative confidence. You light up every room you enter.",
  health: "Prioritize practices that energize and uplift. Embodiment work, creative expression, or energetic healing can support your radiance.",
  mysticMessage: "Your presence is power. Own it fully.",
  journalPrompt: "How would I show up if I trusted my own fire completely?",
  metaDescription: "The Queen of Wands exudes confidence, magnetism, and creative leadership. Command your space with grace."
},
{
  id: "king-of-wands",
  name: "King of Wands",
  number: 36,
  slug: "king-of-wands",
  imageFileName: "KingOfWands_36.jpeg",
  description: "King of Wands embodies mastered creativity and visionary leadership...",
  elementAstrology: "Element: Fire | Astrology: Fire of Fire — Unshakable purpose, bold leadership, and inner fire in action",
  love: "You may be attracting someone magnetic and bold — or being asked to embody that energy yourself. Lead with vision, not ego.",
  career: "It’s time to lead with confidence and big-picture thinking. Your vision matters — don’t downplay it. Others look to you for inspiration.",
  life: "This card calls you to own your place as a creative force. Act with intention. Lead with heart. Build what matters.",
  health: "Maintain strong energy through focus, discipline, and passion. Don’t neglect your inner fire — keep it burning steadily.",
  mysticMessage: "You were born to lead something only you can see. Begin now.",
  journalPrompt: "What vision do I carry — and how can I start living it out loud?",
  metaDescription: "The King of Wands embodies visionary leadership, courage, and charisma. Lead with heart and conviction."
},
{
  id: "ace-of-cups",
  name: "Ace of Cups",
  number: 37,
  slug: "ace-of-cups",
  imageFileName: "AceOfCups_37.jpeg",
  description: "Ace of Cups overflows with the pure potential of emotional and spiritual connection...",
  elementAstrology: "Element: Water | Astrology: Cancer, Scorpio, Pisces — The seed of love, healing, and inner joy",
  love: "New love may be arriving — or a deep emotional opening in your current relationship. Let your heart open. Let yourself feel.",
  career: "Follow what fills your cup. A creative or heart-led opportunity may arise. Success will flow through emotional alignment.",
  life: "This is the beginning of emotional healing, intuitive awakening, or spiritual joy. Let softness lead. Trust the tenderness that rises.",
  health: "Healing is flowing in. Focus on hydration, emotional release, and nourishing connection. Rest near water or in beauty.",
  mysticMessage: "Your heart is a chalice — what do you choose to pour into it?",
  journalPrompt: "What is ready to open in my heart — and what would it feel like to receive it fully?",
  metaDescription: "The Ace of Cups overflows with love, emotion, and divine connection. Open your heart to joy and healing."
},
{
  id: "two-of-cups",
  name: "Two of Cups",
  number: 38,
  slug: "two-of-cups",
  imageFileName: "TwoOfCups_38.jpeg",
  description: "Two of Cups celebrates the power of partnership and emotional connection...",
  elementAstrology: "Element: Water | Astrology: Venus in Cancer — Union, tenderness, and deepening trust",
  love: "Union, reconciliation, or new connection is flowing in. This is heart-meets-heart — a bond of sincerity, mutual respect, and soul recognition.",
  career: "Collaborations thrive under this energy. Choose partners or clients who align emotionally, not just strategically.",
  life: "You’re learning how to truly meet another — and yourself — with compassion. Healing happens in connection.",
  health: "Relationships impact your well-being. Seek support, touch, shared joy. Emotional connection is medicine.",
  mysticMessage: "Love is not a transaction — it’s a meeting of hearts. Let yourself be met.",
  journalPrompt: "How can I show up in deeper harmony — with myself and those I love?",
  metaDescription: "The Two of Cups represents union, partnership, and heartfelt connection. A mirror of mutual love and respect."
},
{
  id: "three-of-cups",
  name: "Three of Cups",
  number: 39,
  slug: "three-of-cups",
  imageFileName: "ThreeOfCups_39.jpeg",
  description: "Three of Cups dances with the joy of friendship and community celebration...",
  elementAstrology: "Element: Water | Astrology: Mercury in Cancer — Joyful connection and emotional bonding",
  love: "This card signals shared joy — in friendship or romance. Emotional bonds are strengthened through celebration, laughter, and mutual care.",
  career: "Celebrate small wins with others. Collaborate, gather, share ideas. Joy fuels productivity and purpose.",
  life: "Let your heart dance with others. Community and connection are healing. Say yes to shared experiences that light you up.",
  health: "Emotional and social nourishment are vital now. Spend time with those who lift your spirit. Play is medicine.",
  mysticMessage: "Joy shared is joy multiplied. Let the good in.",
  journalPrompt: "Who helps me feel free and celebrated — and how can I connect with them more deeply?",
  metaDescription: "The Three of Cups celebrates friendship, sisterhood, and joyful reunion. A toast to shared love and laughter."
},
{
  id: "four-of-cups",
  name: "Four of Cups",
  number: 40,
  slug: "four-of-cups",
  imageFileName: "FourOfCups_40.jpeg",
  description: "Four of Cups contemplates the gifts before us...",
  elementAstrology: "Element: Water | Astrology: Moon in Cancer — Emotional withdrawal, introspection, and reevaluation",
  love: "You may feel emotionally disconnected or unsure. A new opportunity in love may be present — but you’ll need to open your heart to see it.",
  career: "Something feels uninspiring. It’s okay to pause and reflect. But don’t miss a fresh offer because you’re focused on what’s not working.",
  life: "This is a moment of emotional pause. Let yourself rest — but stay open to the quiet invitations the universe is making.",
  health: "Emotional fatigue may be present. Reconnect with yourself through stillness, meditation, and gentle self-care.",
  mysticMessage: "A new blessing may be closer than you think. Look again.",
  journalPrompt: "What emotion am I resisting — and what might happen if I welcomed it in?",
  metaDescription: "The Four of Cups suggests introspection, emotional withdrawal, or apathy. What divine gift are you overlooking?"
},
{
  id: "five-of-cups",
  name: "Five of Cups",
  number: 41,
  slug: "five-of-cups",
  imageFileName: "FiveOfCups_41.jpeg",
  description: "Five of Cups teaches us about loss and the process of emotional healing...",
  elementAstrology: "Element: Water | Astrology: Mars in Scorpio — Deep emotional release, grief, and transformation",
  love: "Heartbreak, regret, or loss may be present — but not all is lost. What remains may be the seed of deeper love. Honor your grief, then look again.",
  career: "A disappointment may have shaken your confidence. Take time to process, then reclaim your power and refocus your vision.",
  life: "Grief is sacred. Let it move through you. But don’t forget — the story isn’t over. Healing and hope still stand behind you.",
  health: "Emotional processing is vital. Tears are release. Let yourself feel fully — and then reach for what supports you now.",
  mysticMessage: "What’s gone may hurt — but what remains still holds love.",
  journalPrompt: "What am I grieving — and what might still be waiting for me behind the pain?",
  metaDescription: "The Five of Cups shows grief, disappointment, or emotional loss. Yet, not all is gone — hope remains behind you."
},
{
  id: "six-of-cups",
  name: "Six of Cups",
  number: 42,
  slug: "six-of-cups",
  imageFileName: "SixOfCups_42.jpeg",
  description: "Six of Cups carries the sweet energy of nostalgia and innocent joy...",
  elementAstrology: "Element: Water | Astrology: Sun in Scorpio — Light shining on the emotional past",
  love: "Past relationships or memories may resurface. This could be a time for sweet reconnection, or healing childhood patterns in love.",
  career: "A project or idea from the past may be ripe for revival. Think creatively — sometimes your younger self had the right instinct.",
  life: "This is a moment to honor the past, but not get stuck there. Let joy, innocence, and play return to your daily experience.",
  health: "Childlike joy is medicine. Reconnect with activities that used to make you feel alive and free. Healing may come through the inner child.",
  mysticMessage: "What once brought you joy still lives within you — go visit it.",
  journalPrompt: "What memory still holds light for me — and how can I let it bloom again now?",
  metaDescription: "The Six of Cups returns you to nostalgia, innocence, and childhood joy. Connect with the simple heart again."
},
{
  id: "seven-of-cups",
  name: "Seven of Cups",
  number: 43,
  slug: "seven-of-cups",
  imageFileName: "SevenOfCups_43.jpeg",
  description: "Seven of Cups opens a realm of possibilities and dreams...",
  elementAstrology: "Element: Water | Astrology: Venus in Scorpio — Desire, temptation, and imaginative vision",
  love: "You may have many choices — or be caught in fantasy. Take time to discern real connection from illusion. Look beyond appearances.",
  career: "So many options, but not all are aligned. Avoid decision paralysis. Tune in to what feels truly resonant and sustainable.",
  life: "Imagination is powerful, but not all dreams are meant to be lived. This is a time to sort the gold from the glitter.",
  health: "Overwhelm or confusion may be clouding your judgment. Get grounded. Trust your gut — not just your fantasies.",
  mysticMessage: "You can dream anything — but you must choose something.",
  journalPrompt: "What dream or desire is real for me — and what’s just a tempting distraction?",
  metaDescription: "The Seven of Cups is illusion, fantasy, and overwhelming choices. Ground yourself before deciding."
},
{
  id: "eight-of-cups",
  name: "Eight of Cups",
  number: 44,
  slug: "eight-of-cups",
  imageFileName: "EightOfCups_44.jpeg",
  description: "Eight of Cups guides us on the journey of emotional growth...",
  elementAstrology: "Element: Water | Astrology: Saturn in Pisces — Letting go of illusion and seeking emotional truth",
  love: "A connection may feel emotionally incomplete. You may be walking away — or choosing to seek something deeper within or beyond.",
  career: "A job or project no longer nourishes your spirit. It’s okay to move on. Something more aligned awaits once you release what’s stale.",
  life: "This is a soul journey — one that requires leaving comfort for truth. You’re not running away. You’re walking toward more.",
  health: "Listen to emotional signals. When something feels off, trust your instinct and make room for change — especially in relationships or environment.",
  mysticMessage: "Leave the empty cup. Seek the stream that fills you.",
  journalPrompt: "What am I being asked to leave — not out of failure, but wisdom?",
  metaDescription: "The Eight of Cups speaks of emotional departure, soul-searching, and inner callings. Leave what no longer fulfills."
},
{
  id: "nine-of-cups",
  name: "Nine of Cups",
  number: 45,
  slug: "nine-of-cups",
  imageFileName: "NineOfCups_45.jpeg",
  description: "Nine of Cups radiates emotional fulfillment and the manifestation of wishes...",
  elementAstrology: "Element: Water | Astrology: Jupiter in Pisces — Contentment, emotional abundance, and spiritual satisfaction",
  love: "Your heart is full — or nearly there. Joy, ease, and self-love attract rich connection. This is your permission to enjoy without apology.",
  career: "A goal may be fulfilled. Celebrate! Your efforts are bringing emotional as well as material satisfaction. Enjoy the success you’ve earned.",
  life: "This is a moment of sweet emotional arrival. It’s okay to bask in gratitude. Let yourself enjoy the pleasure of now.",
  health: "Pleasure supports your healing. Focus on what nourishes you — body and soul. Emotional contentment boosts physical vitality.",
  mysticMessage: "This is the wish granted. Now receive it with an open heart.",
  journalPrompt: "What feels like true abundance to me — and how can I celebrate it today?",
  metaDescription: "The Nine of Cups is the wish card — contentment, pleasure, and satisfaction. Enjoy what you’ve created."
},
{
  id: "ten-of-cups",
  name: "Ten of Cups",
  number: 46,
  slug: "ten-of-cups",
  imageFileName: "TenOfCups_46.jpeg",
  description: "Ten of Cups celebrates complete emotional fulfillment and harmonious relationships...",
  elementAstrology: "Element: Water | Astrology: Mars in Pisces — Unified vision, emotional completion, and shared joy",
  love: "This is the dream — deep connection, shared joy, emotional safety. You may be experiencing or moving toward a lasting bond of love and harmony.",
  career: "You’re building something that aligns with your heart. Teamwork, purpose, and shared values are leading to long-term joy.",
  life: "You are surrounded by love — or being called to create it consciously. Harmony, not perfection, is the key. Cherish what’s real.",
  health: "Emotional wholeness supports physical wellness. Family, chosen family, and heartfelt relationships are part of your healing path.",
  mysticMessage: "Love is the true legacy. Build your life around what matters most.",
  journalPrompt: "What does true emotional fulfillment feel like — and how can I welcome more of it?",
  metaDescription: "The Ten of Cups radiates joy, family harmony, and emotional fulfillment. A rainbow after the storm."
},
{
  id: "page-of-cups",
  name: "Page of Cups",
  number: 47,
  slug: "page-of-cups",
  imageFileName: "PageOfCups_47.jpeg",
  description: "Page of Cups brings messages from the heart and the realm of imagination...",
  elementAstrology: "Element: Water | Astrology: Earth of Water — Sensitive beginnings, emotional messages, creative dreaming",
  love: "A message of affection or a new emotional spark may arrive. Stay open and playful — even if you feel uncertain or vulnerable.",
  career: "A new creative idea or offer may appear unexpectedly. Let your intuition guide your response — logic can come later.",
  life: "This is a time of gentle beginnings. Listen to your dreams, your heart, and your inner child. Something tender is blooming.",
  health: "Emotional sensitivity may be heightened. Art, journaling, and expression can help process and restore balance.",
  mysticMessage: "Your heart is speaking — dare to listen with curiosity.",
  journalPrompt: "What would I hear if I let my heart speak freely — without judgment?",
  metaDescription: "The Page of Cups is gentle wonder, artistic inspiration, and messages from the heart. Stay open to surprise."
},
{
  id: "knight-of-cups",
  name: "Knight of Cups",
  number: 48,
  slug: "knight-of-cups",
  imageFileName: "KnightOfCups_48.jpeg",
  description: "Knight of Cups pursues romantic ideals and emotional quests...",
  elementAstrology: "Element: Water | Astrology: Air of Water — Messenger of dreams, love, and soulful invitations",
  love: "Romance is stirring. A meaningful connection, date, or declaration could be near. This is love with depth — but keep your feet on the ground.",
  career: "A creative or heart-driven offer may appear. Follow your passion — but temper idealism with clarity before committing.",
  life: "You’re on a soulful quest. Beauty, love, and inspiration guide you now. Let your intuition lead, even if the path feels dreamy.",
  health: "Pay attention to emotional signals in the body. Water, music, and gentle practices can support inner peace.",
  mysticMessage: "The quest begins — led not by logic, but by the heart’s song.",
  journalPrompt: "What beautiful vision is calling to me — and am I ready to follow it?",
  metaDescription: "The Knight of Cups rides on romance, beauty, and emotional pursuit. Follow your heart’s quest."
},
{
  id: "queen-of-cups",
  name: "Queen of Cups",
  number: 49,
  slug: "queen-of-cups",
  imageFileName: "QueenOfCups_49.jpeg",
  description: "Queen of Cups embodies emotional wisdom and intuitive understanding...",
  elementAstrology: "Element: Water | Astrology: Water of Water — Deep empathy, psychic awareness, and calm nurturing",
  love: "You are a source of deep emotional nourishment — or being invited to receive it. This is unconditional love — but don’t lose yourself caring for others.",
  career: "Your empathy and intuition are your superpowers. Lean into roles that involve care, creativity, or subtle leadership.",
  life: "This is a time for inner listening. Emotions are sacred guides. Make space for stillness, ritual, and introspection.",
  health: "Water, rest, and emotional balance are key. Protect your sensitivity and stay connected to your own needs.",
  mysticMessage: "Still waters run deep — trust the knowing beneath the surface.",
  journalPrompt: "How can I hold space for my emotions — the way I would for someone I deeply love?",
  metaDescription: "The Queen of Cups is empathy, intuition, and emotional depth. She feels deeply and loves purely."
},
{
  id: "king-of-cups",
  name: "King of Cups",
  number: 50,
  slug: "king-of-cups",
  imageFileName: "KingOfCups_50.jpeg",
  description: "King of Cups masters the art of emotional balance and spiritual wisdom...",
  elementAstrology: "Element: Water | Astrology: Fire of Water — Compassionate command, mature love, and calm in the storm",
  love: "Emotional maturity is the gift here. Whether in partnership or self-work, lead with calm presence and an open heart.",
  career: "Your ability to stay composed and compassionate is needed. You may be guiding others — or asked to manage emotional dynamics with grace.",
  life: "You are mastering emotional intelligence. Stay steady, even as others swirl around you. Your heart is wise — lead from it.",
  health: "Emotional health impacts physical well-being. Practice breathwork, therapy, or other methods that regulate and ground you.",
  mysticMessage: "Lead with calm compassion — your presence heals more than you know.",
  journalPrompt: "What would it look like to trust my emotions — without letting them rule me?",
  metaDescription: "The King of Cups blends emotional mastery with compassion. A calm leader who rules the heart with wisdom."
},
{
  id: "ace-of-swords",
  name: "Ace of Swords",
  number: 51,
  slug: "ace-of-swords",
  imageFileName: "AceOfSwords_51.jpeg",
  description: "Ace of Swords cuts through confusion with the sharp clarity of new insight...",
  elementAstrology: "Element: Air | Astrology: Gemini, Libra, Aquarius — Truth, clarity, communication",
  love: "A breakthrough conversation or realization may arise. Speak your truth — or listen for one. Clarity brings freedom.",
  career: "A new idea, contract, or decision is forming. Stay sharp, focus your mind, and use your voice with power and precision.",
  life: "You’re being handed a sword of truth. Use it to cut through illusion, fear, or old beliefs. Clarity is your ally now.",
  health: "Mental clarity and focus are returning. Clear your space, simplify your inputs, and prioritize your peace of mind.",
  mysticMessage: "Truth is your sword — speak it, live it, honor it.",
  journalPrompt: "What truth wants to be spoken — even if it changes everything?",
  metaDescription: "The Ace of Swords cuts through confusion with truth, clarity, and insight. A breakthrough is at hand."
},
{
  id: "two-of-swords",
  name: "Two of Swords",
  number: 52,
  slug: "two-of-swords",
  imageFileName: "TwoOfSwords_52.jpeg",
  description: "Two of Swords balances opposing thoughts and decisions...",
  elementAstrology: "Element: Air | Astrology: Moon in Libra — Emotional indecision, mental balance",
  love: "You may be torn between two paths, people, or feelings. Don’t rush the choice — give space for inner clarity to rise.",
  career: "You're at a crossroads. Logic alone won’t decide this — tune into what feels right, not just what looks right.",
  life: "You’re suspended between options. This pause is sacred. Trust that clarity will come once you stop forcing an answer.",
  health: "Emotional tension may show up as headaches or mental fatigue. Rest your mind and ground your nervous system before acting.",
  mysticMessage: "Stillness brings truth. Let your mind settle before choosing.",
  journalPrompt: "What is my intuition saying — beneath the noise of overthinking?",
  metaDescription: "The Two of Swords reflects indecision, duality, and a need to trust your inner wisdom. The answer lies within."
},
{
  id: "three-of-swords",
  name: "Three of Swords",
  number: 53,
  slug: "three-of-swords",
  imageFileName: "ThreeOfSwords_53.jpeg",
  description: "Three of Swords pierces the heart with necessary truth...",
  elementAstrology: "Element: Air | Astrology: Saturn in Libra — Difficult truths, emotional maturity",
  love: "A heartbreak, betrayal, or realization may be surfacing. Allow grief — don’t bypass it. There is wisdom in feeling fully.",
  career: "A setback or disappointment may sting. Let it refine, not define you. Honor your emotions, then rise with new clarity.",
  life: "This card reminds you that some pain is part of awakening. Feel it. Speak it. Release it. There’s a clearing on the other side.",
  health: "Emotional wounds may be surfacing in physical form. Address root causes, not just symptoms. Therapy or journaling may support healing.",
  mysticMessage: "Broken hearts reveal hidden truths. Let them speak.",
  journalPrompt: "What truth is breaking me open — and how can I honor the healing it brings?",
  metaDescription: "The Three of Swords brings sorrow, heartbreak, or painful truth. Feel to heal — and begin again."
},
{
  id: "four-of-swords",
  name: "Four of Swords",
  number: 54,
  slug: "four-of-swords",
  imageFileName: "FourOfSwords_54.jpeg",
  description: "Four of Swords offers the gift of rest and renewal...",
  elementAstrology: "Element: Air | Astrology: Jupiter in Libra — Restful expansion, thoughtful pause",
  love: "You may need space — mentally or emotionally — to reset. This isn’t avoidance, it’s restoration. Breathe before re-engaging.",
  career: "Step back to gain perspective. Don’t push right now. Clarity, vision, and creativity return after rest.",
  life: "You are being asked to pause. Let the world go quiet so your soul can speak. Recovery is part of growth.",
  health: "Prioritize sleep, solitude, and nervous system repair. Your energy is returning — give it time to rebuild.",
  mysticMessage: "Rest is not retreat — it’s sacred strategy.",
  journalPrompt: "What part of me is calling for silence, space, and stillness?",
  metaDescription: "The Four of Swords offers rest, recovery, and mental peace. Retreat to restore your spirit."
},
{
  id: "five-of-swords",
  name: "Five of Swords",
  number: 55,
  slug: "five-of-swords",
  imageFileName: "FiveOfSwords_55.jpeg",
  description: "Five of Swords confronts us with the aftermath of conflict...",
  elementAstrology: "Element: Air | Astrology: Venus in Aquarius — Detached conflict, lessons in ego",
  love: "A disagreement may have left lingering tension. Consider: is winning worth the wound? Let go of being right — choose peace instead.",
  career: "Power struggles or unhealthy competition may be surfacing. Protect your peace. Walk away from situations that diminish your integrity.",
  life: "This card asks you to reflect on how you engage with conflict. Not all battles are worth your energy. Choose discernment over domination.",
  health: "Mental stress, migraines, or exhaustion may be signs of emotional overexertion. Step back. Reframe the issue. Breathe.",
  mysticMessage: "You can win the fight — and still lose your peace. Choose wisely.",
  journalPrompt: "Where am I fighting to be right — and what would surrender look like instead?",
  metaDescription: "The Five of Swords shows conflict, ego clashes, or hollow victory. Is the win worth the cost?"
},
{
  id: "six-of-swords",
  name: "Six of Swords",
  number: 56,
  slug: "six-of-swords",
  imageFileName: "SixOfSwords_56.jpeg",
  description: "Six of Swords guides us through transitions and healing journeys...",
  elementAstrology: "Element: Air | Astrology: Mercury in Aquarius — Mental detachment, clear movement",
  love: "You may be healing from heartbreak, or moving through a difficult phase together. Gentle detachment and reflection bring clarity.",
  career: "A transition is happening. You’re leaving old systems or dynamics behind. Trust the new shore you’re heading toward.",
  life: "This is sacred passage — from confusion to clarity, storm to calm. You’re not alone. Spirit guides you forward now.",
  health: "You’re emerging from a time of difficulty. Continue with steady, gentle support — body, mind, and heart are all adjusting.",
  mysticMessage: "The worst is behind you. Keep sailing toward peace.",
  journalPrompt: "What am I ready to move on from — and what healing do I need for the journey?",
  metaDescription: "The Six of Swords marks transition, healing journeys, and moving on. Leave the storm behind."
},
{
  id: "seven-of-swords",
  name: "Seven of Swords",
  number: 57,
  slug: "seven-of-swords",
  imageFileName: "SevenOfSwords_57.jpeg",
  description: "Seven of Swords navigates the complex terrain of strategy and hidden truths...",
  elementAstrology: "Element: Air | Astrology: Moon in Aquarius — Mental strategy, emotional detachment, subtle insight",
  love: "Secrets, self-protection, or avoidance may be at play. Are you being honest — with yourself and others?",
  career: "You may need to act strategically — but beware of cutting ethical corners. Smart choices don’t have to be sneaky ones.",
  life: "This card asks you to examine your motives. Are you being clever — or just escaping discomfort? Authenticity is your guide.",
  health: "Avoidance or secrecy around health issues could be slowing healing. Face what’s been hidden. Truth is the first medicine.",
  mysticMessage: "You don’t need to hide to be safe. Integrity is protection.",
  journalPrompt: "Where am I not being fully honest — and why am I afraid to be?",
  metaDescription: "The Seven of Swords reveals secrets, strategy, or betrayal. Choose wisdom over trickery."
},
{
  id: "eight-of-swords",
  name: "Eight of Swords",
  number: 58,
  slug: "eight-of-swords",
  imageFileName: "EightOfSwords_58.jpeg",
  description: "Eight of Swords illuminates self-imposed limitations and mental constraints...",
  elementAstrology: "Element: Air | Astrology: Jupiter in Gemini — Expansion blocked by fear or overthinking",
  love: "You may feel trapped or unseen. But some of this is internal — shaped by past wounds or limiting beliefs. Freedom begins with perception.",
  career: "A situation may feel restrictive — but look closer. The door is cracked open. You’re more empowered than you think.",
  life: "Fear is fogging your vision. The cage is mental. Breathe, reframe, and remember: you hold the key.",
  health: "Anxiety, overwhelm, or overthinking may be contributing to stagnation. Gentle movement and mental release can help you feel free again.",
  mysticMessage: "You are not truly stuck — only seeing through fear. Look again.",
  journalPrompt: "What thought is keeping me small — and what truth could set me free?",
  metaDescription: "The Eight of Swords symbolizes mental entrapment and self-doubt. Freedom begins in the mind."
},
{
  id: "nine-of-swords",
  name: "Nine of Swords",
  number: 59,
  slug: "nine-of-swords",
  imageFileName: "NineOfSwords_59.jpeg",
  description: "Nine of Swords confronts the shadows of anxiety and mental anguish...",
  elementAstrology: "Element: Air | Astrology: Mars in Gemini — Mental tension, restless worry, sleepless nights",
  love: "Fear, regret, or guilt may be clouding your heart. Speak your truth or seek support — it’s time to lighten the emotional load.",
  career: "Stress and perfectionism may be creating burnout. Step back. Not everything must be solved right now. Prioritize your peace.",
  life: "The monsters in the mind feel real — but they’re not the full truth. Reach out. You’re not alone in the dark.",
  health: "Sleep issues, anxiety, or worry may be affecting your body. Gentle rituals, nervous system care, and kindness are key.",
  mysticMessage: "Your fears are loud — but your truth is louder. Breathe into it.",
  journalPrompt: "What fear keeps visiting me at night — and what truth do I need to whisper back?",
  metaDescription: "The Nine of Swords reflects anxiety, sleepless nights, and inner torment. Name your fears to disarm them."
},
{
  id: "ten-of-swords",
  name: "Ten of Swords",
  number: 60,
  slug: "ten-of-swords",
  imageFileName: "TenOfSwords_60.jpeg",
  description: "Ten of Swords marks the end of a difficult cycle...",
  elementAstrology: "Element: Air | Astrology: Sun in Gemini — Mental exhaustion, clarity through finality",
  love: "A painful ending or betrayal may have occurred. Let yourself grieve. This closure makes way for your rebirth.",
  career: "A chapter is over — possibly not in the way you hoped. But what’s ending was never meant to define you. Begin again, wiser.",
  life: "This is rock bottom — but also the ground beneath your feet. Let it be your turning point. The light is rising.",
  health: "A full reset is needed. Give your body time to release accumulated tension and trauma. Let rest rebuild you.",
  mysticMessage: "It’s over now. Let yourself rise from what’s been laid to rest.",
  journalPrompt: "What final ending must I accept — so something truer can begin?",
  metaDescription: "The Ten of Swords signals painful endings and rock bottom. The worst has passed — now rise."
},
{
  id: "page-of-swords",
  name: "Page of Swords",
  number: 61,
  slug: "page-of-swords",
  imageFileName: "PageOfSwords_61.jpeg",
  description: "Page of Swords embodies mental alertness and the quest for knowledge...",
  elementAstrology: "Element: Air | Astrology: Earth of Air — Curious thoughts, fresh ideas, mental spark",
  love: "You may be overthinking a connection — or someone may be observing you quietly. Clear communication is key. Ask, don’t assume.",
  career: "New ideas, studies, or research opportunities are presenting themselves. Follow your intellectual curiosity — and keep refining your message.",
  life: "Your mind is sharp. Now’s the time to explore, question, and experiment. Curiosity leads to clarity.",
  health: "Pay attention to your thoughts. Your mindset shapes your vitality. Use journaling, therapy, or learning to rewire what isn’t serving.",
  mysticMessage: "Your mind is a sword — use it to carve new truth, not chase old fears.",
  journalPrompt: "What new idea or truth am I ready to explore with an open mind?",
  metaDescription: "The Page of Swords is curiosity, new ideas, and mental agility. Observe, learn, and question everything."
},
{
  id: "knight-of-swords",
  name: "Knight of Swords",
  number: 62,
  slug: "knight-of-swords",
  imageFileName: "KnightOfSwords_62.jpeg",
  description: "Knight of Swords charges forward with intellectual intensity and swift action...",
  elementAstrology: "Element: Air | Astrology: Air of Air — Focused action, mental drive, communication on a mission",
  love: "You may be moving too fast in matters of the heart — or someone around you is. Pause to consider: is your heart aligned with your words?",
  career: "Decisions are flying — and you’re in the thick of it. Move with confidence, but don’t bulldoze. Precision matters more than speed.",
  life: "Your convictions are strong. Use that clarity wisely — but stay open to other perspectives. Truth doesn’t need force to stand strong.",
  health: "Mental overexertion may cause burnout. Pace your mind. Clarity comes not only from speed, but also from pause.",
  mysticMessage: "Let your truth be swift — and also kind.",
  journalPrompt: "Where am I rushing to be heard — and what might change if I paused to truly listen?",
  metaDescription: "The Knight of Swords charges forward with intellect, speed, and fierce determination. Watch your tone and timing."
},
{
  id: "queen-of-swords",
  name: "Queen of Swords",
  number: 63,
  slug: "queen-of-swords",
  imageFileName: "QueenOfSwords_63.jpeg",
  description: "Queen of Swords wields the sword of clear judgment and independent thinking...",
  elementAstrology: "Element: Air | Astrology: Water of Air — Emotional intelligence meets sharp truth",
  love: "This card brings clarity. You see things for what they are — and are unafraid to ask for what you need. Don’t settle for less than truth.",
  career: "Your insights and communication are sharp. Use them to cut through confusion or lead with clarity. Be concise — but not cold.",
  life: "You’ve earned your wisdom. Now speak from it — not bitterness, but grounded knowing. Boundaries are sacred.",
  health: "Clear your mind, organize your priorities, and detach from draining emotional entanglements. Mental clarity supports full wellness.",
  mysticMessage: "Speak the truth. Even if your voice trembles — let it be clear.",
  journalPrompt: "What truth am I ready to own — with compassion and confidence?",
  metaDescription: "The Queen of Swords stands for clarity, honesty, and sharp perception. Speak your truth with compassion."
},
{
  id: "king-of-swords",
  name: "King of Swords",
  number: 64,
  slug: "king-of-swords",
  imageFileName: "KingOfSwords_64.jpeg",
  description: "King of Swords embodies mastered intellect and ethical leadership...",
  elementAstrology: "Element: Air | Astrology: Fire of Air — Strategic vision, truth in leadership, disciplined thought",
  love: "Lead with honesty and emotional maturity. This card asks for clarity in communication — and invites a partner who values truth over charm.",
  career: "Step into authority through wisdom. You are being called to make fair, strategic decisions. Be the leader who listens — and speaks with purpose.",
  life: "You’ve cultivated sharp discernment. Don’t let emotion cloud your clarity. But also — don’t weaponize your intellect. Lead with integrity.",
  health: "Mental structure supports healing. Try breathwork, CBT, or mental clarity practices to support emotional balance.",
  mysticMessage: "Wisdom is not just what you know — it’s how you apply it.",
  journalPrompt: "How can I lead my life from clarity — not control?",
  metaDescription: "The King of Swords embodies reason, integrity, and authority. Lead with logic and truth."
},
{
  id: "ace-of-pentacles",
  name: "Ace of Pentacles",
  number: 65,
  slug: "ace-of-pentacles",
  imageFileName: "AceOfPentacles_65.jpeg",
  description: "Ace of Pentacles plants the seed of material opportunity and manifestation...",
  elementAstrology: "Element: Earth | Astrology: Taurus, Virgo, Capricorn — Material beginnings, grounded blessings",
  love: "A new relationship may take root — one with long-term potential. Ground your emotions and let this grow slowly and steadily.",
  career: "A financial offer or stable opportunity may be emerging. This is the start of something tangible — tend to it like a garden.",
  life: "This is the seed of prosperity. Your actions today will shape your foundation tomorrow. Nurture it with presence.",
  health: "Grounding, nutrition, and physical care are key. Start simple — habits grow slowly, but surely, into wholeness.",
  mysticMessage: "What begins now can become something lasting — if you commit to its care.",
  journalPrompt: "What new foundation am I ready to plant — and how can I tend it with love?",
  metaDescription: "The Ace of Pentacles offers grounded beginnings, prosperity, and tangible blessings. Plant the seed of abundance."
},
{
  id: "two-of-pentacles",
  name: "Two of Pentacles",
  number: 66,
  slug: "two-of-pentacles",
  imageFileName: "TwoOfPentacles_66.jpeg",
  description: "Two of Pentacles dances with the rhythms of balance and adaptation...",
  elementAstrology: "Element: Earth | Astrology: Jupiter in Capricorn — Flexible discipline, multitasking mastery",
  love: "You're juggling priorities — and your connection may need more attention. Balance doesn’t mean equal time — it means mindful presence.",
  career: "Your plate is full. Use time-blocking, prioritization, and adaptability to manage responsibilities without burning out.",
  life: "This card invites harmony in motion. Don't aim for perfect balance — aim for presence amid the flow.",
  health: "Work-life imbalance could be taking a toll. Recalibrate. Add grounding routines and simplify where possible.",
  mysticMessage: "You don’t need to do everything — just what truly matters.",
  journalPrompt: "Where am I stretched too thin — and what can I let go to restore harmony?",
  metaDescription: "The Two of Pentacles represents balance, flexibility, and juggling priorities. Flow with life's ups and downs."
},
{
  id: "three-of-pentacles",
  name: "Three of Pentacles",
  number: 67,
  slug: "three-of-pentacles",
  imageFileName: "ThreeOfPentacles_67.jpeg",
  description: "Three of Pentacles celebrates craftsmanship and collaborative effort...",
  elementAstrology: "Element: Earth | Astrology: Mars in Capricorn — Purposeful work and structured cooperation",
  love: "You and your partner are building something real. Focus on teamwork, shared goals, and mutual respect.",
  career: "Collaboration is the key to long-term success. Each person’s skill matters — including yours. Don’t underestimate what you bring.",
  life: "This is the time to work toward mastery — not alone, but in community. Create something lasting with aligned people.",
  health: "Work with practitioners, guides, or a support system. Your growth is supported when you don’t go it alone.",
  mysticMessage: "Great work takes great unity. Honor every brick laid — and those who lay them beside you.",
  journalPrompt: "Who are my true collaborators — and how can we build something beautiful together?",
  metaDescription: "The Three of Pentacles signifies collaboration, skill, and shared vision. Progress comes from teamwork."
},
{
  id: "four-of-pentacles",
  name: "Four of Pentacles",
  number: 68,
  slug: "four-of-pentacles",
  imageFileName: "FourOfPentacles_68.jpeg",
  description: "Four of Pentacles holds tight to established security...",
  elementAstrology: "Element: Earth | Astrology: Sun in Capricorn — Security, boundaries, cautious holding",
  love: "You or your partner may be guarded. Is fear of loss blocking emotional flow? Open slowly — but do open.",
  career: "You may be playing it safe — and that’s okay for now. But ask: is fear of risk keeping you from expansion?",
  life: "Security is sacred — but clinging too tightly can create stagnation. Trust that you can hold what matters without gripping in fear.",
  health: "Tension may manifest in the body. Breathwork and somatic release can help create space for new energy to flow.",
  mysticMessage: "You are safe — even if you let go.",
  journalPrompt: "Where am I clinging — and what would looseness feel like instead?",
  metaDescription: "The Four of Pentacles warns of holding too tightly — to money, fear, or control. True security comes from flow."
},
{
  id: "five-of-pentacles",
  name: "Five of Pentacles",
  number: 69,
  slug: "five-of-pentacles",
  imageFileName: "FiveOfPentacles_69.jpeg",
  description: "Five of Pentacles walks through times of material hardship and spiritual testing...",
  elementAstrology: "Element: Earth | Astrology: Mercury in Taurus — Scarcity mindset, external trials",
  love: "Loneliness or disconnection may feel acute. But support is closer than you think. Reach out — love doesn’t need to be earned.",
  career: "A period of financial instability or loss may be present. Ask for help, simplify expenses, and remember: this is temporary.",
  life: "You may feel shut out — emotionally, spiritually, or materially. But you are not alone. Seek warmth, support, and shelter in community.",
  health: "Fatigue or illness may be tied to emotional depletion. Rest. Nourish. Accept support with grace.",
  mysticMessage: "Even in your lowest moment — the light is still glowing nearby. Look up.",
  journalPrompt: "What support am I ready to receive — even if my pride resists it?",
  metaDescription: "The Five of Pentacles shows hardship, loss, or isolation. Support is closer than you think — reach out."
},
{
  id: "six-of-pentacles",
  name: "Six of Pentacles",
  number: 70,
  slug: "six-of-pentacles",
  imageFileName: "SixOfPentacles_70.jpeg",
  description: "Six of Pentacles embodies the flow of giving and receiving...",
  elementAstrology: "Element: Earth | Astrology: Moon in Taurus — Generosity, balanced exchange, energetic reciprocity",
  love: "Give and take are key. Are both partners contributing and receiving in harmony? Check in with your balance of emotional investment.",
  career: "A gift, loan, or opportunity may arrive. Or perhaps it’s time for you to offer guidance or resources to someone else. Either way — share wisely.",
  life: "What you give comes back. Check where your generosity flows — and where you might need to receive with more openness.",
  health: "Energetic imbalance may be present. Give to yourself what you give to others. Rest is not a reward — it’s required.",
  mysticMessage: "Life flows when generosity meets boundaries. Let the current move both ways.",
  journalPrompt: "Where am I giving too much — or not allowing myself to receive enough?",
  metaDescription: "The Six of Pentacles reflects giving and receiving, generosity, and shared wealth. Balance flows in exchange."
},
{
  id: "seven-of-pentacles",
  name: "Seven of Pentacles",
  number: 71,
  slug: "seven-of-pentacles",
  imageFileName: "SevenOfPentacles_71.jpeg",
  description: "Seven of Pentacles pauses to evaluate progress and long-term investments...",
  elementAstrology: "Element: Earth | Astrology: Saturn in Taurus — Patient growth, sustainability, long view",
  love: "You may be reassessing a relationship’s future. Is it growing as hoped? Water what works — prune what doesn’t.",
  career: "Pause and evaluate. The seeds you’ve planted are growing — but are they bearing the right fruit? Adjust if needed.",
  life: "You’re in a cycle of reflection. Not all slow growth is stagnation. Let long-term vision guide you now.",
  health: "A lifestyle shift may be necessary for sustainable wellness. What’s working? What’s draining? Realign gently.",
  mysticMessage: "Patience isn’t waiting — it’s preparing for harvest.",
  journalPrompt: "What long-term vision am I tending — and is it still worth the effort?",
  metaDescription: "The Seven of Pentacles is patience, long-term investment, and reassessment. Tend your garden with care."
},
{
  id: "eight-of-pentacles",
  name: "Eight of Pentacles",
  number: 72,
  slug: "eight-of-pentacles",
  imageFileName: "EightOfPentacles_72.jpeg",
  description: "Eight of Pentacles focuses on skill development and dedicated work...",
  elementAstrology: "Element: Earth | Astrology: Sun in Virgo — Focused practice, mastery in motion",
  love: "Love is built — not just felt. Consistency, care, and effort deepen intimacy. Be present for the daily beauty of tending.",
  career: "You’re on the path to mastery. Keep refining. This is about focused diligence — not overnight success.",
  life: "This is your workshop season. Each action, though small, is shaping your future. Keep showing up — it matters.",
  health: "Small, repeated choices shape your vitality. Focus on systems, routines, and tiny daily wins. They add up.",
  mysticMessage: "Mastery lives in the mundane. Let devotion be your magic.",
  journalPrompt: "What am I ready to build through steady, soul-filled practice?",
  metaDescription: "The Eight of Pentacles is mastery, diligence, and focused effort. Your craft is refining — keep going."
},
{
  id: "nine-of-pentacles",
  name: "Nine of Pentacles",
  number: 73,
  slug: "nine-of-pentacles",
  imageFileName: "NineOfPentacles_73.jpeg",
  description: "Nine of Pentacles cultivates refined abundance and self-sufficiency...",
  elementAstrology: "Element: Earth | Astrology: Venus in Virgo — Pleasure in solitude, independence, earned elegance",
  love: "You are whole. Any relationship must meet you there — not complete you. Celebrate your independence and high standards.",
  career: "You’ve created something of real value. Pause to enjoy the harvest. Self-made success is worth savoring.",
  life: "This is a time of grace, refinement, and sovereign power. Own your achievements and rest in your self-worth.",
  health: "Well-being is a ritual. Let beauty, nature, and gentle structure guide your vitality now.",
  mysticMessage: "You are already enough. Everything else is decoration.",
  journalPrompt: "Where can I celebrate my independence — without apology or explanation?",
  metaDescription: "The Nine of Pentacles celebrates independence, self-worth, and earned luxury. Bask in your cultivated success."
},
{
  id: "ten-of-pentacles",
  name: "Ten of Pentacles",
  number: 74,
  slug: "ten-of-pentacles",
  imageFileName: "TenOfPentacles_74.jpeg",
  description: "Ten of Pentacles establishes lasting wealth and legacy...",
  elementAstrology: "Element: Earth | Astrology: Mercury in Virgo — Legacy through structure, wisdom, and generational care",
  love: "Stability, family, and long-term commitment are themes now. Build a love that supports future generations.",
  career: "Your work may be entering a stage of legacy. Think long-term: What systems or structures will outlast you?",
  life: "This is about roots — home, ancestry, tradition. Honor where you come from as you build what comes next.",
  health: "Focus on long-term wellness — not quick fixes. Think in decades. What practices will carry you into old age with grace?",
  mysticMessage: "Legacy isn’t built in a moment — it’s built in every moment.",
  journalPrompt: "What does lasting abundance look like — and how am I creating it now?",
  metaDescription: "The Ten of Pentacles is legacy, wealth, and family foundations. Long-term stability is yours."
},
{
  id: "page-of-pentacles",
  name: "Page of Pentacles",
  number: 75,
  slug: "page-of-pentacles",
  imageFileName: "PageOfPentacles_75.jpeg",
  description: "Page of Pentacles approaches material opportunities with studious dedication...",
  elementAstrology: "Element: Earth | Astrology: Earth of Earth — Focused curiosity, grounded beginnings, student of the path",
  love: "This is new, slow love — or a growing bond rooted in trust. Take your time. Explore steadily, with care.",
  career: "You’re beginning something real — a new job, study path, or business idea. Be patient and curious. The ground is fertile.",
  life: "Now is the time to learn, plant, and nurture. Your actions are forming strong roots. Go slow, stay steady.",
  health: "Focus on routines, planning, and consistency. Your body wants simplicity and sustainable care.",
  mysticMessage: "Begin as a student — and let your devotion shape your future.",
  journalPrompt: "What new journey am I ready to commit to — one grounded in real growth?",
  metaDescription: "The Page of Pentacles brings study, opportunity, and grounded curiosity. A seed of success is being planted."
},
{
  id: "knight-of-pentacles",
  name: "Knight of Pentacles",
  number: 76,
  slug: "knight-of-pentacles",
  imageFileName: "KnightOfPentacles_76.jpeg",
  description: "Knight of Pentacles advances steadily toward goals with unwavering dedication...",
  elementAstrology: "Element: Earth | Astrology: Air of Earth — Methodical progress, quiet strength, discipline with devotion",
  love: "This is the slow burn — reliable, consistent, and deeply devoted. Not flashy, but strong. Let love grow at its pace.",
  career: "You’re building something lasting. Results may be slow, but they’re solid. Keep showing up — even when no one’s watching.",
  life: "This is the long road — and you’re walking it well. Trust the pace. Consistency is your magic now.",
  health: "Sustainable habits are more powerful than short bursts. Build a foundation — and stick to it.",
  mysticMessage: "Faith in the process creates results worth waiting for.",
  journalPrompt: "What am I tending daily — and how does it reflect the life I’m creating?",
  metaDescription: "The Knight of Pentacles is persistence, loyalty, and steady progress. Keep going — even slow steps matter."
},
{
  id: "queen-of-pentacles",
  name: "Queen of Pentacles",
  number: 77,
  slug: "queen-of-pentacles",
  imageFileName: "QueenOfPentacles_77.jpeg",
  description: "Queen of Pentacles nurtures prosperity through practical wisdom and generous care...",
  elementAstrology: "Element: Earth | Astrology: Water of Earth — Emotional nourishment meets material mastery",
  love: "You offer warmth, stability, and support — or are calling that in. Domestic harmony and sensual grounding are highlighted now.",
  career: "Abundance flows from your practical magic. You’re a nurturer, a planner, a provider — and it’s being recognized.",
  life: "This card invites you to root into safety, softness, and generosity. Build your life like a sacred garden — with care and strength.",
  health: "Care for your body like a beloved child. Nourishment, routine, and rest are sacred acts.",
  mysticMessage: "Prosperity is the result of love made practical.",
  journalPrompt: "How can I nourish the physical and emotional roots of my well-being?",
  metaDescription: "The Queen of Pentacles nurtures abundance, home, and practicality. Grounded love creates lasting beauty."
},
{
  id: "king-of-pentacles",
  name: "King of Pentacles",
  number: 78,
  slug: "king-of-pentacles",
  imageFileName: "KingOfPentacles_78.jpeg",
  description: "King of Pentacles masters the realm of material abundance and practical achievement...",
  elementAstrology: "Element: Earth | Astrology: Fire of Earth — Grounded leadership, wealth built with integrity",
  love: "Loyalty, commitment, and deep protection define this energy. If you're seeking love, look for (or become) the partner who builds a strong foundation with care.",
  career: "You’re reaching a peak of success. Lead with generosity, mentor others, and continue building with integrity. You're here to leave a legacy.",
  life: "You are the rock — steady, wise, and rooted. Enjoy the fruits of your labor, but remember: wealth is best shared and stewarded with heart.",
  health: "Grounded routines and holistic habits serve you now. Your physical and financial health are intertwined — nurture both wisely.",
  mysticMessage: "True richness lies not just in what you have — but in how you hold it.",
  journalPrompt: "How can I embody steady, wise leadership — and what legacy am I choosing to create?",
  metaDescription: "The King of Pentacles represents success, stability, and wise leadership. Prosper through patience and vision."
},

];

// Helper function to get a card by its number (1-78)
export const getCardByNumber = (number: number): TarotCard | undefined =>
  allTarotCards.find(card => card.number === number);

// Helper function to get a card by its id (slug)
export const getCardById = (id: string): TarotCard | undefined =>
  allTarotCards.find(card => card.id === id);

// You might want to add a check to ensure allTarotCards is not empty
if (allTarotCards.length < 78 && process.env.NODE_ENV === 'development') {
  console.warn(`Warning: Only ${allTarotCards.length} cards loaded into tarot-data.ts. Expected 78.`);
}
if (allTarotCards.length === 0 && process.env.NODE_ENV !== 'test') {
    throw new Error("No tarot cards loaded. Please check src/lib/tarot-data.ts");
}