[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"

[[redirects]]
  from = "http://mysticaltarotgarden.netlify.app/*"
  to = "https://mysticaltarotgarden.netlify.app/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "https://mysticaltarotgarden.netlify.app/:splat"
  status = 301
  force = true
  conditions = { Host = "www.mysticaltarotgarden.netlify.app" }
